special_fireball_transition_frame_l 1 13
special_fireball_transition_frame_m 1 13
special_fireball_transition_frame_h 1 13
special_fireball_transition_frame_ex 1 13
special_slide_transition_frame 1 27
special_slide_move_start_frame 1 2
special_slide_move_stop_frame 1 31
special_slide_move_x_l 2 17.0
special_slide_move_x_m 2 17.0
special_slide_move_x_h 2 22.0
special_slide_move_x_ex 2 22.0
special_uppercut_transition_frame 1 9
special_uppercut_move_frame 1 4
special_uppercut_x_l 2 6.0
special_uppercut_x_m 2 6.0
special_uppercut_x_h 2 6.0
special_uppercut_x_ex 2 6.0
special_uppercut_init_y_l 2 20.0
special_uppercut_init_y_m 2 20.0
special_uppercut_init_y_h 2 25.0
special_uppercut_init_y_ex 2 25.0
special_uppercut_gravity_l 2 2.0
special_uppercut_gravity_m 2 1.5
special_uppercut_gravity_h 2 1.5
special_uppercut_gravity_ex 2 1.5
special_uppercut_fall_speed_l 2 12.0
special_uppercut_fall_speed_m 2 12.0
special_uppercut_fall_speed_h 2 12.0
special_uppercut_fall_speed_ex 2 12.0