#pragma once
#include "FighterStatus.h"

enum {
	_CHARA_ANGELICA_STATUS_START = FIGHTER_STATUS_MAX,
	_CHARA_ANGELICA_STATUS_MAX,
};

const int CHARA_ANGELICA_STATUS_START = _CHARA_ANGELICA_STATUS_START;
const int CHARA_ANGELICA_STATUS_MAX = _CHARA_ANGELICA_STATUS_MAX;