#pragma once
#include "FighterFloat.h"

enum {
	_CHARA_ANGELICA_FLOAT_START = FIGHTER_FLOAT_MAX,
	_CHARA_ANGELICA_FLOAT_MAX,
};

const int CHARA_ANGELICA_FLOAT_START = _CHARA_ANGELICA_FLOAT_START;
const int CHARA_ANGELICA_FLOAT_MAX = _CHARA_ANGELICA_FLOAT_MAX;