#pragma once

#define HITBOX_COUNT_MAX 9

enum AttackLevel {
	ATTACK_LEVEL_LIGHT,
	ATTACK_LEVEL_MEDIUM,
	ATTACK_LEVEL_HEAVY,

	ATTACK_LEVEL_MAX,
};

enum ClankKind {
	CLANK_KIND_NORMAL,
	CLANK_KIND_CLANK,
	CLANK_KIND_CONTINUE,

	CLANK_KIND_MAX,
};

enum HitStatus {
	HIT_STATUS_NORMAL,
	HIT_STATUS_CRUMPLE,
	HIT_STATUS_LAUNCH,
	HIT_STATUS_BLOWBACK,
	HIT_STATUS_KNOCKDOWN,

	HIT_STATUS_MAX,
};

enum CounterhitType {
	COUNTERHIT_TYPE_NONE,
	COUNTERHIT_TYPE_AERIAL,
	COUNTERHIT_TYPE_NORMAL,

	COUNTERHIT_TYPE_MAX,
};

enum KoKind {
	KO_KIND_NORMAL,
	KO_KIND_NONE,
	KO_KIND_CHIP,

	KO_KIND_MAX,
};

enum GrabboxKind {
	GRABBOX_KIND_NORMAL,
	GRABBOX_KIND_NOTECH,
	GRABBOX_KIND_HITSTUN,
	GRABBOX_KIND_HITSTUN_NOTECH,

	GRABBOX_KIND_MAX,
};

enum HurtboxKind {
	HURTBOX_KIND_NORMAL,
	HURTBOX_KIND_COUNTER,
	HURTBOX_KIND_RIGHT_OF_WAY,

	HURTBOX_KIND_MAX,
};

enum IntangibleKind {
	INTANGIBLE_KIND_HIGH,
	INTANGIBLE_KIND_MID,
	INTANGIBLE_KIND_LOW,
	INTANGIBLE_KIND_NONE,
	INTANGIBLE_KIND_THROW,
	INTANGIBLE_KIND_NORMAL,
	INTANGIBLE_KIND_PROJECTILE,
	INTANGIBLE_KIND_INVINCIBLE,
	INTANGIBLE_KIND_ALL,

	INTANGIBLE_KIND_MAX,
};

enum AttackHeight {
	ATTACK_HEIGHT_HIGH,
	ATTACK_HEIGHT_MID,
	ATTACK_HEIGHT_LOW,

	ATTACK_HEIGHT_MAX,
};

enum SituationHit {
	SITUATION_HIT_GROUND,
	SITUATION_HIT_AIR,
	SITUATION_HIT_DOWN,
	SITUATION_HIT_GROUND_AIR,
	SITUATION_HIT_ALL,

	SITUATION_HIT_MAX,
};