#pragma once

#define HITBOX_COUNT_MAX 9

enum AttackLevel {
	ATTACK_LEVEL_LIGHT,
	ATTACK_LEVEL_MEDIUM,
	ATTACK_LEVEL_HEAVY,

	ATTACK_LEVEL_MAX,
};

enum ClankKind {
	CLANK_KIND_NORMAL,
	CLANK_KIND_CLANK,
	CLANK_KIND_CONTINUE,

	CLANK_KIND_MAX,
};

enum HitStatus {
	HIT_STATUS_NORMAL,
	HIT_STATUS_CRUMPLE,
	HIT_STATUS_FLOAT,
	HIT_STATUS_LAUNCH,
	HIT_STATUS_KNOCKDOWN,

	HIT_STATUS_MAX,
};

enum CounterhitType {
	COUNTERHIT_TYPE_NONE,
	COUNTERHIT_TYPE_NORMAL,
	COUNTERHIT_TYPE_PUNISH,
	COUNTERHIT_TYPE_COUNTER_ONLY,
	COUNTERHIT_TYPE_PUNISH_ONLY,
	COUNTERHIT_TYPE_AERIAL_ONLY,

	COUNTERHIT_TYPE_MAX,
};

enum DamageKind {
	DAMAGE_KIND_NORMAL,
	DAMAGE_KIND_NO_KO,
	DAMAGE_KIND_CHIP,
	DAMAGE_KIND_CHIP_KO,

	DAMAGE_KIND_MAX,
};

enum GrabboxKind {
	GRABBOX_KIND_NORMAL,
	GRABBOX_KIND_NOTECH,
	GRABBOX_KIND_HITSTUN,
	GRABBOX_KIND_HITSTUN_NOTECH,

	GRABBOX_KIND_MAX,
};

enum HurtboxKind {
	HURTBOX_KIND_NORMAL,
	HURTBOX_KIND_COUNTER,
	HURTBOX_KIND_RIGHT_OF_WAY,

	HURTBOX_KIND_MAX,
};

enum IntangibleKind {
	INTANGIBLE_KIND_HIGH,
	INTANGIBLE_KIND_MID,
	INTANGIBLE_KIND_LOW,
	INTANGIBLE_KIND_NONE,
	INTANGIBLE_KIND_AERIAL,
	INTANGIBLE_KIND_THROW,
	INTANGIBLE_KIND_STRIKE,
	INTANGIBLE_KIND_PROJECTILE,
	INTANGIBLE_KIND_INVINCIBLE,
	INTANGIBLE_KIND_SOFT,

	INTANGIBLE_KIND_MAX,
};

enum AttackHeight {
	ATTACK_HEIGHT_HIGH,
	ATTACK_HEIGHT_MID,
	ATTACK_HEIGHT_LOW,

	ATTACK_HEIGHT_MAX,
};

enum HitKind {
	HIT_KIND_GROUND = 1,
	HIT_KIND_AIR = 2,
	HIT_KIND_DOWN = 4,
	HIT_KIND_PROJECTILE = 8,
	HIT_KIND_SOFT_INTANGIBLE = 16,
	HIT_KIND_ARMOR = 32,

	HIT_KIND_MAX,
};

inline HitKind operator|(HitKind a, HitKind b)
{
	return static_cast<HitKind>(static_cast<int>(a) | static_cast<int>(b));
}