#pragma once
#include "FighterFlag.h"

enum {
	_CHARA_BRUNO_FLAG_START = FIGHTER_FLAG_MAX,
	_CHARA_BRUNO_FLAG_MAX,
};

const int CHARA_BRUNO_FLAG_START = _CHARA_BRUNO_FLAG_START;
const int CHARA_BRUNO_FLAG_MAX = _CHARA_BRUNO_FLAG_MAX;