#pragma once
#include "FighterFlag.h"

enum {
	_CHARA_CHARA_TEMPLATE_FLAG_START = FIGHTER_FLAG_MAX,
	_CHARA_CHARA_TEMPLATE_FLAG_MAX,
};

const int CHARA_CHARA_TEPLATE_FLAG_START = _CHARA_CHARA_TEMPLATE_FLAG_START;
const int CHARA_CHARA_TEMPLATE_FLAG_MAX = _CHARA_CHARA_TEMPLATE_FLAG_MAX;