#pragma once

#define CSS_SLOTS 32
#define NUM_COLS 10
#define NUM_ROWS 4
#define CSS_WIDTH WINDOW_WIDTH * 0.8
#define CSS_HEIGHT WINDOW_HEIGHT / 2.5

enum CharaSelectionState {
	CHARA_SELECTION_STATE_DESELECTED,
	CHARA_SELECTION_STATE_SELECTED_CHARA,
	CHARA_SELECTION_STATE_SELECTED_COLOR,

	CHARA_SELECTION_STATE_MAX
};