#pragma once

enum {
	CHARA_KIND_ROWAN,
	CHARA_KIND_ERIC,
	CHARA_KIND_LEON,
	CHARA_KIND_ANGELICA,
	CHARA_KIND_NIGHTSABER,
	CHARA_KIND_SULLY,
	CHARA_KIND_ROOK,
	CHARA_KIND_DANTE,
	CHARA_KIND_BRUNO,
	CHARA_KIND_TESSA,
	CHARA_KIND_ZYAIR,
	CHARA_KIND_NORMAN,
	CHARA_KIND_ATLAS,
	CHARA_KIND_JULIUS,
	CHARA_KIND_RAMONA,
	CHARA_KIND_HUNTER,
	CHARA_KIND_VESUVIUS,

	CHARA_KIND_CHAMELEON,

	CHARA_KIND_CHARA_TEMPLATE,
	CHARA_KIND_MAX,
};