#pragma once
#include "FighterStatus.h"

enum {
	_CHARA_CHARA_TEMPLATE_STATUS_START = FIGHTER_STATUS_MAX,
	_CHARA_CHARA_TEMPLATE_STATUS_TEMPLATE,
	_CHARA_CHARA_TEMPLATE_STATUS_MAX,
};

const int CHARA_CHARA_TEMPLATE_STATUS_START = _CHARA_CHARA_TEMPLATE_STATUS_START;
const int CHARA_CHARA_TEMPLATE_STATUS_TEMPLATE = _CHARA_CHARA_TEMPLATE_STATUS_TEMPLATE;
const int CHARA_CHARA_TEMPLATE_STATUS_MAX = _CHARA_CHARA_TEMPLATE_STATUS_MAX;