#pragma once

#define CSS_SLOTS 32
#define NUM_COLS 10
#define NUM_ROWS 4
#define CSS_WIDTH WINDOW_WIDTH * 0.8
#define CSS_HEIGHT WINDOW_HEIGHT / 2.5

enum {
	CHARA_SELECT_GROUP_MISC,
	CHARA_SELECT_GROUP_SLOT,

	CHARA_SELECT_GROUP_MAX
};

enum {
	CHARA_SELECT_MISC_BG,
	CHARA_SELECT_MISC_CURSOR,

	CHARA_SELECT_MISC_MAX
};