#pragma once
#include "FighterInt.h"

enum {
	_CHARA_DESIRAE_INT_START = FIGHTER_INT_MAX,
	_CHARA_DESIRAE_INT_MAX,
};

const int CHARA_DESIRAE_INT_START = _CHARA_DESIRAE_INT_START;
const int CHARA_DESIRAE_INT_MAX = _CHARA_DESIRAE_INT_MAX;