#pragma once
#include "FighterString.h"

enum {
	_CHARA_DESIRAE_STRING_START = FIGHTER_STRING_MAX,
	_CHARA_DESIRAE_STRING_MAX,
};

const int CHARA_DESIRAE_STRING_START = _CHARA_DESIRAE_STRING_START;
const int CHARA_DESIRAE_STRING_MAX = _CHARA_DESIRAE_STRING_MAX;