#pragma once
#include "FighterInt.h"

enum {
	_CHARA_ERIC_INT_START = FIGHTER_INT_MAX,
	_CHARA_ERIC_INT_DISCHARGE_LEVEL,
	_CHARA_ERIC_INT_MAX,
};

const int CHARA_ERIC_INT_START = _CHARA_ERIC_INT_START;
const int CHARA_ERIC_INT_DISCHARGE_LEVEL = _CHARA_ERIC_INT_DISCHARGE_LEVEL;
const int CHARA_ERIC_INT_MAX = _CHARA_ERIC_INT_MAX;
