#pragma once
#include "ProjectileStatus.h"

enum {
	PROJECTILE_ERIC_FIREBALL_STATUS_START = PROJECTILE_STATUS_MAX,
	PROJECTILE_ERIC_FIREBALL_STATUS_HOVER,
	PROJECTILE_ERIC_FIREBALL_STATUS_KICKED,
	PROJECTILE_ERIC_FIREBALL_STATUS_MAX,
};