#pragma once
#include "FighterStatus.h"

enum {
	CHARA_ERIC_STATUS_SPECIAL_FIREBALL = FIGHTER_STATUS_MAX,
	CHARA_ERIC_STATUS_SPECIAL_UPPERCUT_START,
	CHARA_ERIC_STATUS_SPECIAL_UPPERCUT,
	CHARA_ERIC_STATUS_SPECIAL_UPPERCUT_FALL,
	CHARA_ERIC_STATUS_MAX,
};