#pragma once
#include "FighterFlag.h"

enum {
	_CHARA_ERIC_FLAG_START = FIGHTER_FLAG_MAX,
	_CHARA_ERIC_FLAG_OVERDRIVEN,
	_CHARA_ERIC_FLAG_MAX,
};

const int CHARA_ERIC_FLAG_START = _CHARA_ERIC_FLAG_START;
const int CHARA_ERIC_FLAG_OVERDRIVEN = _CHARA_ERIC_FLAG_OVERDRIVEN;
const int CHARA_ERIC_FLAG_MAX = _CHARA_ERIC_FLAG_MAX;