#pragma once
#include "FighterStatus.h"

enum {
	_CHARA_ERIC_STATUS_SPECIAL_FIREBALL = FIGHTER_STATUS_MAX,
	_CHARA_ERIC_STATUS_SPECIAL_UPPERCUT_START,
	_CHARA_ERIC_STATUS_SPECIAL_UPPERCUT,
	_CHARA_ERIC_STATUS_SPECIAL_UPPERCUT_FALL,
	_CHARA_ERIC_STATUS_MAX,
};

const int CHARA_ERIC_STATUS_SPECIAL_FIREBALL = _CHARA_ERIC_STATUS_SPECIAL_FIREBALL;
const int CHARA_ERIC_STATUS_SPECIAL_UPPERCUT_START = _CHARA_ERIC_STATUS_SPECIAL_UPPERCUT_START;
const int CHARA_ERIC_STATUS_SPECIAL_UPPERCUT = _CHARA_ERIC_STATUS_SPECIAL_UPPERCUT;
const int CHARA_ERIC_STATUS_SPECIAL_UPPERCUT_FALL = _CHARA_ERIC_STATUS_SPECIAL_UPPERCUT_FALL;
const int CHARA_ERIC_STATUS_MAX = _CHARA_ERIC_STATUS_MAX;