#pragma once
#include "ProjectileInt.h"

enum {
	_PROJECTILE_ERIC_FIREBALL_INT_START = PROJECTILE_INT_MAX,

	_PROJECTILE_ERIC_FIREBALL_INT_MAX,
};

const int PROJECTILE_ERIC_FIREBALL_INT_START = _PROJECTILE_ERIC_FIREBALL_INT_START;
const int PROJECTILE_ERIC_FIREBALL_INT_MAX = _PROJECTILE_ERIC_FIREBALL_INT_MAX;