#pragma once
#include "ProjectileFloat.h"

enum {
	_PROJECTILE_ERIC_FIREBALL_FLOAT_START = PROJECTILE_FLOAT_MAX,

	_PROJECTILE_ERIC_FIREBALL_FLOAT_MAX,
};

const int PROJECTILE_ERIC_FIREBALL_FLOAT_START = _PROJECTILE_ERIC_FIREBALL_FLOAT_START;
const int PROJECTILE_ERIC_FIREBALL_FLOAT_MAX = _PROJECTILE_ERIC_FIREBALL_FLOAT_MAX;