#pragma once
#include "FighterString.h"

enum {
	_CHARA_ERIC_STRING_START = FIGHTER_STRING_MAX,
	_CHARA_ERIC_STRING_MAX,
};

const int CHARA_ERIC_STRING_START = _CHARA_ERIC_STRING_START;
const int CHARA_ERIC_STRING_MAX = _CHARA_ERIC_STRING_MAX;