#pragma once
#include "FighterFloat.h"

enum {
	_CHARA_ERIC_FLOAT_START = FIGHTER_FLOAT_MAX,
	_CHARA_ERIC_FLOAT_MAX,
};

const int CHARA_ERIC_FLOAT_START = _CHARA_ERIC_FLOAT_START;
const int CHARA_ERIC_FLOAT_MAX = _CHARA_ERIC_FLOAT_MAX;