#pragma once

const int FIGHTER_SITUATION_GROUND = 0;
const int FIGHTER_SITUATION_AIR = 1;
const int FIGHTER_SITUATION_DOWN = 2;
const int FIGHTER_SITUATION_MAX = 3;

const int STATUS_GROUP_NORMAL = 0;
const int STATUS_GROUP_HITSTUN = 1;
const int STATUS_GROUP_CROUCH = 2;
const int STATUS_GROUP_ATTACK = 3;
const int STATUS_GROUP_LANDING = 4;
const int STATUS_GROUP_MAX = 5;

const int DASH_CANCEL_KIND_NONE = 0;
const int DASH_CANCEL_KIND_WHIFF_PUNISH_OFFENSIVE = 1;
const int DASH_CANCEL_KIND_WHIFF_PUNISH_DEFENSIVE = 2;
const int DASH_CANCEL_KIND_INFINITE = 3;
const int DASH_CANCEL_KIND_MAX = 4;

const int JUMP_KIND_F = 0;
const int JUMP_KIND_B = 1;
const int JUMP_KIND_N = 2;
const int JUMP_KIND_MAX = 3;

const int HITSTUN_HEIGHT_NONE = 0;
const int HITSTUN_HEIGHT_STAND = 1;
const int HITSTUN_HEIGHT_FORCE_STAND = 2;
const int HITSTUN_HEIGHT_CROUCH = 3;
const int HITSTUN_HEIGHT_FORCE_CROUCH = 4;
const int HITSTUN_HEIGHT_MAX = 5;

const int PARRY_HEIGHT_HIGH = 0;
const int PARRY_HEIGHT_MID = 1;
const int PARRY_HEIGHT_LOW = 2;
const int PARRY_HEIGHT_ALL = 3;
const int PARRY_HEIGHT_MAX = 4;

const int SPECIAL_LEVEL_L = 0;
const int SPECIAL_LEVEL_M = 1;
const int SPECIAL_LEVEL_H = 2;
const int SPECIAL_LEVEL_EX = 3;
const int SPECIAL_LEVEL_N = 4;
const int SPECIAL_LEVEL_MAX = 5;

const int WAKEUP_TYPE_DEFAULT = 0;
const int WAKEUP_TYPE_FAST = 1;
const int WAKEUP_TYPE_BACK = 2;
const int WAKEUP_TYPE_MAX = 3;

const int UI_TEXT_TYPE_NONE = 0;
const int UI_TEXT_TYPE_COUNTER = 1;
const int UI_TEXT_TYPE_COUNTER_PUNISH = 2;
const int UI_TEXT_TYPE_COUNTER_HITSTUN_PARRY = 3;
const int UI_TEXT_TYPE_COUNTER_JUMP = 4;
const int UI_TEXT_TYPE_ARMOR_BREAK = 5;
const int UI_TEXT_TYPE_REVERSAL = 6;

const int COUNTERHIT_VAL_NONE = 0;
const int COUNTERHIT_VAL_COUNTER = 1;
const int COUNTERHIT_VAL_PUNISH = 2;
const int COUNTERHIT_VAL_CRIT_STATUS = 3;