#pragma once

enum {
	_FIGHTER_STRING_MOVE_KIND,
	_FIGHTER_STRING_HITSTUN_ANIM,
	_FIGHTER_STRING_MAX
};

const int FIGHTER_STRING_MOVE_KIND = _FIGHTER_STRING_MOVE_KIND;
const int FIGHTER_STRING_HITSTUN_ANIM = _FIGHTER_STRING_HITSTUN_ANIM;
const int FIGHTER_STRING_MAX = _FIGHTER_STRING_MAX;