#pragma once

enum {
	_FIGHTER_STATUS_NONE,
	_FIGHTER_STATUS_WAIT,
	_FIGHTER_STATUS_WALK_F,
	_FIGHTER_STATUS_WALK_B,
	_FIGHTER_STATUS_DASH_F,
	_FIGHTER_STATUS_DASH_B,
	_FIGHTER_STATUS_DASH_AIR,
	_FIGHTER_STATUS_CROUCH_D,
	_FIGHTER_STATUS_CROUCH,
	_FIGHTER_STATUS_CROUCH_U,
	_FIGHTER_STATUS_JUMPSQUAT,
	_FIGHTER_STATUS_JUMP,
	_FIGHTER_STATUS_FALL,
	_FIGHTER_STATUS_TURN,
	_FIGHTER_STATUS_ATTACK,
	_FIGHTER_STATUS_ATTACK_AIR,
	_FIGHTER_STATUS_ADVANCE,
	_FIGHTER_STATUS_ADVANCE_FORWARD,
	_FIGHTER_STATUS_ADVANCE_BACK,
	_FIGHTER_STATUS_GRAB,
	_FIGHTER_STATUS_THROW,
	_FIGHTER_STATUS_GRAB_AIR,
	_FIGHTER_STATUS_THROW_AIR,
	_FIGHTER_STATUS_GRABBED,
	_FIGHTER_STATUS_THROWN,
	_FIGHTER_STATUS_HITSTUN,
	_FIGHTER_STATUS_HITSTUN_AIR,
	_FIGHTER_STATUS_HITSTUN_FLOAT,
	_FIGHTER_STATUS_BLOCKSTUN,
	_FIGHTER_STATUS_PARRY_START,
	_FIGHTER_STATUS_HITSTUN_PARRY_START,
	_FIGHTER_STATUS_LAUNCH_PARRY_START,
	_FIGHTER_STATUS_PARRY,
	_FIGHTER_STATUS_CRUMPLE,
	_FIGHTER_STATUS_LAUNCH_START,
	_FIGHTER_STATUS_LAUNCH,
	_FIGHTER_STATUS_CLANK,
	_FIGHTER_STATUS_THROW_TECH,
	_FIGHTER_STATUS_LANDING,
	_FIGHTER_STATUS_LANDING_ATTACK,
	_FIGHTER_STATUS_LANDING_HITSTUN,
	_FIGHTER_STATUS_KNOCKDOWN_START,
	_FIGHTER_STATUS_KNOCKDOWN,
	_FIGHTER_STATUS_WAKEUP,
	_FIGHTER_STATUS_TAUNT,
	_FIGHTER_STATUS_ROUND_END,

	_FIGHTER_STATUS_MAX,
	_FIGHTER_STATUS_START_CHARA_STATUS,
};

const int FIGHTER_STATUS_NONE = _FIGHTER_STATUS_NONE;
const int FIGHTER_STATUS_WAIT = _FIGHTER_STATUS_WAIT;
const int FIGHTER_STATUS_WALK_F = _FIGHTER_STATUS_WALK_F;
const int FIGHTER_STATUS_WALK_B = _FIGHTER_STATUS_WALK_B;
const int FIGHTER_STATUS_DASH_F = _FIGHTER_STATUS_DASH_F;
const int FIGHTER_STATUS_DASH_B = _FIGHTER_STATUS_DASH_B;
const int FIGHTER_STATUS_DASH_AIR = _FIGHTER_STATUS_DASH_AIR;
const int FIGHTER_STATUS_CROUCH_D = _FIGHTER_STATUS_CROUCH_D;
const int FIGHTER_STATUS_CROUCH = _FIGHTER_STATUS_CROUCH;
const int FIGHTER_STATUS_CROUCH_U = _FIGHTER_STATUS_CROUCH_U;
const int FIGHTER_STATUS_JUMPSQUAT = _FIGHTER_STATUS_JUMPSQUAT;
const int FIGHTER_STATUS_JUMP = _FIGHTER_STATUS_JUMP;
const int FIGHTER_STATUS_FALL = _FIGHTER_STATUS_FALL;
const int FIGHTER_STATUS_TURN = _FIGHTER_STATUS_TURN;
const int FIGHTER_STATUS_ATTACK = _FIGHTER_STATUS_ATTACK;
const int FIGHTER_STATUS_ATTACK_AIR = _FIGHTER_STATUS_ATTACK_AIR;
const int FIGHTER_STATUS_ADVANCE = _FIGHTER_STATUS_ADVANCE;
const int FIGHTER_STATUS_ADVANCE_FORWARD = _FIGHTER_STATUS_ADVANCE_FORWARD;
const int FIGHTER_STATUS_ADVANCE_BACK = _FIGHTER_STATUS_ADVANCE_BACK;
const int FIGHTER_STATUS_GRAB = _FIGHTER_STATUS_GRAB;
const int FIGHTER_STATUS_THROW = _FIGHTER_STATUS_THROW;
const int FIGHTER_STATUS_GRAB_AIR = _FIGHTER_STATUS_GRAB_AIR;
const int FIGHTER_STATUS_THROW_AIR = _FIGHTER_STATUS_THROW_AIR;
const int FIGHTER_STATUS_GRABBED = _FIGHTER_STATUS_GRABBED;
const int FIGHTER_STATUS_THROWN = _FIGHTER_STATUS_THROWN;
const int FIGHTER_STATUS_HITSTUN = _FIGHTER_STATUS_HITSTUN;
const int FIGHTER_STATUS_HITSTUN_AIR = _FIGHTER_STATUS_HITSTUN_AIR;
const int FIGHTER_STATUS_HITSTUN_FLOAT = _FIGHTER_STATUS_HITSTUN_FLOAT;
const int FIGHTER_STATUS_BLOCKSTUN = _FIGHTER_STATUS_BLOCKSTUN;
const int FIGHTER_STATUS_PARRY_START = _FIGHTER_STATUS_PARRY_START;
const int FIGHTER_STATUS_HITSTUN_PARRY_START = _FIGHTER_STATUS_HITSTUN_PARRY_START;
const int FIGHTER_STATUS_LAUNCH_PARRY_START = _FIGHTER_STATUS_LAUNCH_PARRY_START;
const int FIGHTER_STATUS_PARRY = _FIGHTER_STATUS_PARRY;
const int FIGHTER_STATUS_CRUMPLE = _FIGHTER_STATUS_CRUMPLE;
const int FIGHTER_STATUS_LAUNCH_START = _FIGHTER_STATUS_LAUNCH_START;
const int FIGHTER_STATUS_LAUNCH = _FIGHTER_STATUS_LAUNCH;
const int FIGHTER_STATUS_CLANK = _FIGHTER_STATUS_CLANK;
const int FIGHTER_STATUS_THROW_TECH = _FIGHTER_STATUS_THROW_TECH;
const int FIGHTER_STATUS_LANDING = _FIGHTER_STATUS_LANDING;
const int FIGHTER_STATUS_LANDING_ATTACK = _FIGHTER_STATUS_LANDING_ATTACK;
const int FIGHTER_STATUS_LANDING_HITSTUN = _FIGHTER_STATUS_LANDING_HITSTUN;
const int FIGHTER_STATUS_KNOCKDOWN_START = _FIGHTER_STATUS_KNOCKDOWN_START;
const int FIGHTER_STATUS_KNOCKDOWN = _FIGHTER_STATUS_KNOCKDOWN;
const int FIGHTER_STATUS_WAKEUP = _FIGHTER_STATUS_WAKEUP;
const int FIGHTER_STATUS_TAUNT = _FIGHTER_STATUS_TAUNT;
const int FIGHTER_STATUS_ROUND_END = _FIGHTER_STATUS_ROUND_END;

const int FIGHTER_STATUS_MAX = _FIGHTER_STATUS_MAX;
const int FIGHTER_STATUS_START_CHARA_STATUS = _FIGHTER_STATUS_START_CHARA_STATUS;