#pragma once

enum {
	FIGHTER_FLAG_SHORT_HOP,
	FIGHTER_FLAG_DASH_CANCEL,
	FIGHTER_FLAG_ATTACK_CONNECTED,
	FIGHTER_FLAG_ATTACK_CONNECTED_DURING_STATUS,
	FIGHTER_FLAG_ATTACK_BLOCKED_DURING_STATUS,
	FIGHTER_FLAG_HAS_ATTACK,
	FIGHTER_FLAG_HAD_ATTACK_IN_STATUS,
	FIGHTER_FLAG_SUCCESSFUL_PARRY,
	FIGHTER_FLAG_PARRY_ACTIVE,
	FIGHTER_FLAG_PROX_GUARD,
	FIGHTER_FLAG_ENTER_BLOCKSTUN,
	FIGHTER_FLAG_ENABLE_COUNTERHIT,
	FIGHTER_FLAG_USED_AIRDASH,
	FIGHTER_FLAG_THROW_TECH,
	FIGHTER_FLAG_PROJECTILE_CONNECTED_DURING_STATUS,
	FIGHTER_FLAG_ALLOW_GROUND_CROSSUP,
	FIGHTER_FLAG_CAN_TECH,
	FIGHTER_FLAG_FORCE_ANIM_CENTER,
	FIGHTER_FLAG_THREW_OPPONENT,
	FIGHTER_FLAG_STATIONARY_ANIMATION,
	FIGHTER_FLAG_BUFFER_HITLAG_STATUS_SEPARATE,
	FIGHTER_FLAG_BUFFER_HITLAG_STATUS_END,

	FIGHTER_FLAG_MAX,
};

enum {
	CHARA_ROY_FLAG_PLACEHOLDER,
	CHARA_ROY_FLAG_MAX,
};

enum {
	CHARA_ERIC_FLAG_OVERDRIVEN,
	CHARA_ERIC_FLAG_MAX,
};

enum {
	CHARA_LEON_FLAG_START,
	CHARA_LEON_FLAG_MAX,
};

enum {
	CHARA_ANGELICA_FLAG_START,
	CHARA_ANGELICA_FLAG_MAX,
};

enum {
	CHARA_NIGHTSABER_FLAG_START,
	CHARA_NIGHTSABER_FLAG_MAX,
};

enum {
	CHARA_SULLY_FLAG_START,
	CHARA_SULLY_FLAG_MAX,
};

enum {
	CHARA_PRIEST_FLAG_START,
	CHARA_PRIEST_FLAG_MAX,
};

enum {
	CHARA_AZIEL_FLAG_START,
	CHARA_AZIEL_FLAG_MAX,
};

enum {
	CHARA_BRUNO_FLAG_START,
	CHARA_BRUNO_FLAG_MAX,
};

enum {
	CHARA_TESSA_FLAG_START,
	CHARA_TESSA_FLAG_MAX,
};

enum {
	CHARA_ALEJANDRO_FLAG_START,
	CHARA_ALEJANDRO_FLAG_MAX,
};

enum {
	CHARA_NORMAN_FLAG_START,
	CHARA_NORMAN_FLAG_MAX,
};

enum {
	CHARA_ATLAS_FLAG_START,
	CHARA_ATLAS_FLAG_MAX,
};

enum {
	CHARA_JULIUS_FLAG_START,
	CHARA_JULIUS_FLAG_MAX,
};

enum {
	CHARA_RAMONA_FLAG_START,
	CHARA_RAMONA_FLAG_MAX,
};

enum {
	CHARA_ZYAIR_FLAG_START,
	CHARA_ZYAIR_FLAG_MAX,
};

enum {
	CHARA_VESUVIUS_FLAG_START,
	CHARA_VESUVIUS_FLAG_MAX,
};

enum {
	CHARA_CHARA_TEMPLATE_FLAG_START,
	CHARA_CHARA_TEMPLATE_FLAG_MAX,
};