#pragma once

enum {
	 _FIGHTER_INT_JUMP_KIND,
	 _FIGHTER_INT_DASH_F_WINDOW,
	 _FIGHTER_INT_DASH_B_WINDOW,
	 _FIGHTER_INT_KNOCKDOWN_TECH_WINDOW,
	 _FIGHTER_INT_DASH_AIR_DIR,
	 _FIGHTER_INT_BACK_CHARGE_FRAMES,
	 _FIGHTER_INT_BACK_CHARGE_TIMER,
	 _FIGHTER_INT_DOWN_CHARGE_FRAMES,
	 _FIGHTER_INT_DOWN_CHARGE_TIMER,
	 _FIGHTER_INT_PARRY_HEIGHT,
	 _FIGHTER_INT_INIT_HITLAG_FRAMES,
	 _FIGHTER_INT_HITLAG_FRAMES,
	 _FIGHTER_INT_HITSTUN_FRAMES,
	 _FIGHTER_INT_PUSHBACK_FRAMES,
	 _FIGHTER_INT_HITSTUN_LEVEL,
	 _FIGHTER_INT_HITSTUN_HEIGHT,
	 _FIGHTER_INT_BLOCKSTUN_HEIGHT,
	 _FIGHTER_INT_ATTACK_KIND,
	 _FIGHTER_INT_LANDING_LAG,
	 _FIGHTER_INT_JUGGLE_VALUE,
	 _FIGHTER_INT_DAMAGE_SCALE,
	 _FIGHTER_INT_WAKEUP_SPEED,
	 _FIGHTER_INT_236_STEP,
	 _FIGHTER_INT_236_TIMER,
	 _FIGHTER_INT_214_STEP,
	 _FIGHTER_INT_214_TIMER,
	 _FIGHTER_INT_623_STEP,
	 _FIGHTER_INT_623_TIMER,
	 _FIGHTER_INT_41236_STEP,
	 _FIGHTER_INT_41236_TIMER,
	 _FIGHTER_INT_63214_STEP,
	 _FIGHTER_INT_63214_TIMER,
	 _FIGHTER_INT_236236_STEP,
	 _FIGHTER_INT_236236_TIMER,
	 _FIGHTER_INT_214214_STEP,
	 _FIGHTER_INT_214214_TIMER,
	 _FIGHTER_INT_SPECIAL_LEVEL,
	 _FIGHTER_INT_GRAB_INIT_POS_CHANGE_FRAMES,
	 _FIGHTER_INT_GRAB_POS_CHANGE_FRAMES,
	 _FIGHTER_INT_GRAB_BONE_ID,
	 _FIGHTER_INT_GRABBED_BONE_ID,
	 _FIGHTER_INT_BUFFER_HITLAG_STATUS,
	 _FIGHTER_INT_COMBO_COUNT,
	 _FIGHTER_INT_FRAME_ADVANTAGE,

	 _FIGHTER_INT_MAX,
};

const int FIGHTER_INT_JUMP_KIND = _FIGHTER_INT_JUMP_KIND;
const int FIGHTER_INT_DASH_F_WINDOW = _FIGHTER_INT_DASH_F_WINDOW;
const int FIGHTER_INT_DASH_B_WINDOW = _FIGHTER_INT_DASH_B_WINDOW;
const int FIGHTER_INT_KNOCKDOWN_TECH_WINDOW = _FIGHTER_INT_KNOCKDOWN_TECH_WINDOW;
const int FIGHTER_INT_DASH_AIR_DIR = _FIGHTER_INT_DASH_AIR_DIR;
const int FIGHTER_INT_BACK_CHARGE_FRAMES = _FIGHTER_INT_BACK_CHARGE_FRAMES;
const int FIGHTER_INT_BACK_CHARGE_TIMER = _FIGHTER_INT_BACK_CHARGE_TIMER;
const int FIGHTER_INT_DOWN_CHARGE_FRAMES = _FIGHTER_INT_DOWN_CHARGE_FRAMES;
const int FIGHTER_INT_DOWN_CHARGE_TIMER = _FIGHTER_INT_DOWN_CHARGE_TIMER;
const int FIGHTER_INT_PARRY_HEIGHT = _FIGHTER_INT_PARRY_HEIGHT;
const int FIGHTER_INT_INIT_HITLAG_FRAMES = _FIGHTER_INT_INIT_HITLAG_FRAMES;
const int FIGHTER_INT_HITLAG_FRAMES = _FIGHTER_INT_HITLAG_FRAMES;
const int FIGHTER_INT_HITSTUN_FRAMES = _FIGHTER_INT_HITSTUN_FRAMES;
const int FIGHTER_INT_PUSHBACK_FRAMES = _FIGHTER_INT_PUSHBACK_FRAMES;
const int FIGHTER_INT_HITSTUN_LEVEL = _FIGHTER_INT_HITSTUN_LEVEL;
const int FIGHTER_INT_HITSTUN_HEIGHT = _FIGHTER_INT_HITSTUN_HEIGHT;
const int FIGHTER_INT_BLOCKSTUN_HEIGHT = _FIGHTER_INT_BLOCKSTUN_HEIGHT;
const int FIGHTER_INT_ATTACK_KIND = _FIGHTER_INT_ATTACK_KIND;
const int FIGHTER_INT_LANDING_LAG = _FIGHTER_INT_LANDING_LAG;
const int FIGHTER_INT_JUGGLE_VALUE = _FIGHTER_INT_JUGGLE_VALUE;
const int FIGHTER_INT_DAMAGE_SCALE = _FIGHTER_INT_DAMAGE_SCALE;
const int FIGHTER_INT_WAKEUP_SPEED = _FIGHTER_INT_WAKEUP_SPEED;
const int FIGHTER_INT_236_STEP = _FIGHTER_INT_236_STEP;
const int FIGHTER_INT_236_TIMER = _FIGHTER_INT_236_TIMER;
const int FIGHTER_INT_214_STEP = _FIGHTER_INT_214_STEP;
const int FIGHTER_INT_214_TIMER = _FIGHTER_INT_214_TIMER;
const int FIGHTER_INT_623_STEP = _FIGHTER_INT_623_STEP;
const int FIGHTER_INT_623_TIMER = _FIGHTER_INT_623_TIMER;
const int FIGHTER_INT_41236_STEP = _FIGHTER_INT_41236_STEP;
const int FIGHTER_INT_41236_TIMER = _FIGHTER_INT_41236_TIMER;
const int FIGHTER_INT_63214_STEP = _FIGHTER_INT_63214_STEP;
const int FIGHTER_INT_63214_TIMER = _FIGHTER_INT_63214_TIMER;
const int FIGHTER_INT_236236_STEP = _FIGHTER_INT_236236_STEP;
const int FIGHTER_INT_236236_TIMER = _FIGHTER_INT_236236_TIMER;
const int FIGHTER_INT_214214_STEP = _FIGHTER_INT_214214_STEP;
const int FIGHTER_INT_214214_TIMER = _FIGHTER_INT_214214_TIMER;
const int FIGHTER_INT_SPECIAL_LEVEL = _FIGHTER_INT_SPECIAL_LEVEL;
const int FIGHTER_INT_GRAB_INIT_POS_CHANGE_FRAMES = _FIGHTER_INT_GRAB_INIT_POS_CHANGE_FRAMES;
const int FIGHTER_INT_GRAB_POS_CHANGE_FRAMES = _FIGHTER_INT_GRAB_POS_CHANGE_FRAMES;
const int FIGHTER_INT_GRAB_BONE_ID = _FIGHTER_INT_GRAB_BONE_ID;
const int FIGHTER_INT_GRABBED_BONE_ID = _FIGHTER_INT_GRABBED_BONE_ID;
const int FIGHTER_INT_BUFFER_HITLAG_STATUS = _FIGHTER_INT_BUFFER_HITLAG_STATUS;
const int FIGHTER_INT_COMBO_COUNT = _FIGHTER_INT_COMBO_COUNT;
const int FIGHTER_INT_FRAME_ADVANTAGE = _FIGHTER_INT_FRAME_ADVANTAGE;

const int FIGHTER_INT_MAX = _FIGHTER_INT_MAX;