#pragma once

enum {
	_FIGHTER_FLOAT_HEALTH,
	_FIGHTER_FLOAT_PARTIAL_HEALTH,
	_FIGHTER_FLOAT_EX_METER,
	_FIGHTER_FLOAT_SUPER_METER,
	_FIGHTER_FLOAT_INIT_POS_JUMP_Y,
	_FIGHTER_FLOAT_CURRENT_X_SPEED,
	_FIGHTER_FLOAT_CURRENT_Y_SPEED,
	_FIGHTER_FLOAT_LAUNCH_GRAVITY,
	_FIGHTER_FLOAT_LAUNCH_FALL_SPEED_MAX,
	_FIGHTER_FLOAT_LAUNCH_SPEED_X,
	_FIGHTER_FLOAT_LAUNCH_SPEED_Y,
	_FIGHTER_FLOAT_PUSHBACK_PER_FRAME,
	_FIGHTER_FLOAT_GRAB_OFFSET_X,
	_FIGHTER_FLOAT_GRAB_OFFSET_Y,
	_FIGHTER_FLOAT_GRAB_OFFSET_Z,
	_FIGHTER_FLOAT_PREV_WORLD_RATE,
	_FIGHTER_FLOAT_LAST_DAMAGE,
	_FIGHTER_FLOAT_LAST_DAMAGE_SCALE,
	_FIGHTER_FLOAT_COMBO_DAMAGE,
	
	_FIGHTER_FLOAT_MAX,
};

const int FIGHTER_FLOAT_HEALTH = _FIGHTER_FLOAT_HEALTH;
const int FIGHTER_FLOAT_PARTIAL_HEALTH = _FIGHTER_FLOAT_PARTIAL_HEALTH;
const int FIGHTER_FLOAT_EX_METER = _FIGHTER_FLOAT_EX_METER;
const int FIGHTER_FLOAT_SUPER_METER = _FIGHTER_FLOAT_SUPER_METER;
const int FIGHTER_FLOAT_INIT_POS_JUMP_Y = _FIGHTER_FLOAT_INIT_POS_JUMP_Y;
const int FIGHTER_FLOAT_CURRENT_X_SPEED = _FIGHTER_FLOAT_CURRENT_X_SPEED;
const int FIGHTER_FLOAT_CURRENT_Y_SPEED = _FIGHTER_FLOAT_CURRENT_Y_SPEED;
const int FIGHTER_FLOAT_LAUNCH_GRAVITY = _FIGHTER_FLOAT_LAUNCH_GRAVITY;
const int FIGHTER_FLOAT_LAUNCH_FALL_SPEED_MAX = _FIGHTER_FLOAT_LAUNCH_FALL_SPEED_MAX;
const int FIGHTER_FLOAT_LAUNCH_SPEED_X = _FIGHTER_FLOAT_LAUNCH_SPEED_X;
const int FIGHTER_FLOAT_LAUNCH_SPEED_Y = _FIGHTER_FLOAT_LAUNCH_SPEED_Y;
const int FIGHTER_FLOAT_PUSHBACK_PER_FRAME = _FIGHTER_FLOAT_PUSHBACK_PER_FRAME;
const int FIGHTER_FLOAT_GRAB_OFFSET_X = _FIGHTER_FLOAT_GRAB_OFFSET_X;
const int FIGHTER_FLOAT_GRAB_OFFSET_Y = _FIGHTER_FLOAT_GRAB_OFFSET_Y;
const int FIGHTER_FLOAT_GRAB_OFFSET_Z = _FIGHTER_FLOAT_GRAB_OFFSET_Z;
const int FIGHTER_FLOAT_PREV_WORLD_RATE = _FIGHTER_FLOAT_PREV_WORLD_RATE;
const int FIGHTER_FLOAT_LAST_DAMAGE = _FIGHTER_FLOAT_LAST_DAMAGE;
const int FIGHTER_FLOAT_LAST_DAMAGE_SCALE = _FIGHTER_FLOAT_LAST_DAMAGE_SCALE;
const int FIGHTER_FLOAT_COMBO_DAMAGE = _FIGHTER_FLOAT_COMBO_DAMAGE;

const int FIGHTER_FLOAT_MAX = _FIGHTER_FLOAT_MAX;
