#pragma once

enum {
	FIGHTER_FLOAT_HEALTH,
	FIGHTER_FLOAT_SUPER_METER,
	FIGHTER_FLOAT_INIT_POS_JUMP_Y,
	FIGHTER_FLOAT_CURRENT_X_SPEED,
	FIGHTER_FLOAT_CURRENT_Y_SPEED,
	FIGHTER_FLOAT_INIT_LAUNCH_SPEED,
	FIGHTER_FLOAT_LAUNCH_GRAVITY,
	FIGHTER_FLOAT_LAUNCH_FALL_SPEED_MAX,
	FIGHTER_FLOAT_LAUNCH_SPEED_X,
	FIGHTER_FLOAT_PUSHBACK_PER_FRAME,
	FIGHTER_FLOAT_MANUAL_POS_CHANGE_X,
	FIGHTER_FLOAT_MANUAL_POS_CHANGE_Y,
	FIGHTER_FLOAT_MANUAL_POS_OFFSET_X,
	FIGHTER_FLOAT_MANUAL_POS_OFFSET_Y,
	FIGHTER_FLOAT_DISTANCE_TO_WALL,

	FIGHTER_FLOAT_MAX,
};

enum {
	CHARA_ROY_FLOAT_PLACEHOLDER,
	CHARA_ROY_FLOAT_MAX,
};

enum {
	CHARA_ERIC_FLOAT_PLACEHOLDER,
	CHARA_ERIC_FLOAT_MAX,
};

enum {
	CHARA_LEON_FLOAT_START,
	CHARA_LEON_FLOAT_MAX,
};

enum {
	CHARA_ANGELICA_FLOAT_START,
	CHARA_ANGELICA_FLOAT_MAX,
};

enum {
	CHARA_NIGHTSABER_FLOAT_START,
	CHARA_NIGHTSABER_FLOAT_MAX,
};

enum {
	CHARA_SULLY_FLOAT_START,
	CHARA_SULLY_FLOAT_MAX,
};

enum {
	CHARA_PRIEST_FLOAT_START,
	CHARA_PRIEST_FLOAT_MAX,
};

enum {
	CHARA_AZIEL_FLOAT_START,
	CHARA_AZIEL_FLOAT_MAX,
};

enum {
	CHARA_BRUNO_FLOAT_START,
	CHARA_BRUNO_FLOAT_MAX,
};

enum {
	CHARA_TESSA_FLOAT_START,
	CHARA_TESSA_FLOAT_MAX,
};

enum {
	CHARA_ALEJANDRO_FLOAT_START,
	CHARA_ALEJANDRO_FLOAT_MAX,
};

enum {
	CHARA_NORMAN_FLOAT_START,
	CHARA_NORMAN_FLOAT_MAX,
};

enum {
	CHARA_ATLAS_FLOAT_START,
	CHARA_ATLAS_FLOAT_MAX,
};

enum {
	CHARA_JULIUS_FLOAT_START,
	CHARA_JULIUS_FLOAT_MAX,
};

enum {
	CHARA_RAMONA_FLOAT_START,
	CHARA_RAMONA_FLOAT_MAX,
};

enum {
	CHARA_ZYAIR_FLOAT_START,
	CHARA_ZYAIR_FLOAT_MAX,
};

enum {
	CHARA_VESUVIUS_FLOAT_START,
	CHARA_VESUVIUS_FLOAT_MAX,
};

enum {
	CHARA_CHARA_TEMPLATE_FLOAT_START,
	CHARA_CHARA_TEMPLATE_FLOAT_MAX,
};