#pragma once
enum {
	FIGHTER_STATUS_WAIT,
	FIGHTER_STATUS_WALKF,
	FIGHTER_STATUS_WALKB,
	FIGHTER_STATUS_DASH,
	FIGHTER_STATUS_DASHB,
	FIGHTER_STATUS_DASH_AIR,
	FIGHTER_STATUS_CROUCHD,
	FIGHTER_STATUS_CROUCH,
	FIGHTER_STATUS_CROUCHU,
	FIGHTER_STATUS_JUMPSQUAT,
	FIGHTER_STATUS_JUMP,
	FIGHTER_STATUS_FALL,
	FIGHTER_STATUS_ATTACK,
	FIGHTER_STATUS_ATTACK_AIR,
	FIGHTER_STATUS_GRAB,
	FIGHTER_STATUS_THROW,
	FIGHTER_STATUS_GRAB_AIR,
	FIGHTER_STATUS_THROW_AIR,
	FIGHTER_STATUS_GRABBED,
	FIGHTER_STATUS_THROWN,
	FIGHTER_STATUS_HITSTUN,
	FIGHTER_STATUS_HITSTUN_AIR,
	FIGHTER_STATUS_BLOCKSTUN,
	FIGHTER_STATUS_PARRY_START,
	FIGHTER_STATUS_PARRY,
	FIGHTER_STATUS_HITSTUN_PARRY,
	FIGHTER_STATUS_CRUMPLE,
	FIGHTER_STATUS_LAUNCH_START,
	FIGHTER_STATUS_LAUNCH,
	FIGHTER_STATUS_CLANK,
	FIGHTER_STATUS_THROW_TECH,
	FIGHTER_STATUS_LANDING,
	FIGHTER_STATUS_LANDING_ATTACK,
	FIGHTER_STATUS_LANDING_HITSTUN,
	FIGHTER_STATUS_KNOCKDOWN_START,
	FIGHTER_STATUS_KNOCKDOWN,
	FIGHTER_STATUS_WAKEUP,

	FIGHTER_STATUS_MAX,
};

enum {
	CHARA_ROY_STATUS_SPECIAL_FIREBALL_START = FIGHTER_STATUS_MAX,
	CHARA_ROY_STATUS_SPECIAL_FIREBALL_PUNCH,
	CHARA_ROY_STATUS_SPECIAL_FIREBALL_KICK,
	CHARA_ROY_STATUS_SPECIAL_UPPERCUT_START,
	CHARA_ROY_STATUS_SPECIAL_UPPERCUT,
	CHARA_ROY_STATUS_SPECIAL_UPPERCUT_FALL,
	CHARA_ROY_STATUS_MAX,
};

enum {
	CHARA_ERIC_STATUS_SPECIAL_FIREBALL = FIGHTER_STATUS_MAX,
	CHARA_ERIC_STATUS_SPECIAL_UPPERCUT_START,
	CHARA_ERIC_STATUS_SPECIAL_UPPERCUT,
	CHARA_ERIC_STATUS_SPECIAL_UPPERCUT_FALL,
	CHARA_ERIC_STATUS_MAX,
};

enum {
	CHARA_LEON_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_LEON_STATUS_MAX,
};

enum {
	CHARA_ANGELICA_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_ANGELICA_STATUS_MAX,
};

enum {
	CHARA_NIGHTSABER_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_NIGHTSABER_STATUS_MAX,
};

enum {
	CHARA_SULLY_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_SULLY_STATUS_MAX,
};

enum {
	CHARA_PRIEST_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_PRIEST_STATUS_MAX,
};

enum {
	CHARA_AZIEL_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_AZIEL_STATUS_MAX,
};

enum {
	CHARA_BRUNO_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_BRUNO_STATUS_MAX,
};

enum {
	CHARA_TESSA_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_TESSA_STATUS_MAX,
};

enum {
	CHARA_ALEJANDRO_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_ALEJANDRO_STATUS_MAX,
};

enum {
	CHARA_NORMAN_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_NORMAN_STATUS_MAX,
};

enum {
	CHARA_ATLAS_STATUS_SPECIAL_START = FIGHTER_STATUS_MAX,
	CHARA_ATLAS_STATUS_MAX,
};

enum {
	CHARA_JULIUS_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_JULIUS_STATUS_MAX,
};

enum {
	CHARA_RAMONA_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_RAMONA_STATUS_MAX,
};

enum {
	CHARA_ZYAIR_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_ZYAIR_STATUS_MAX,
};

enum {
	CHARA_VESUVIUS_STATUS_START = FIGHTER_STATUS_MAX,
	CHARA_VESUVIUS_STATUS_MAX,
};

enum {
	CHARA_CHARA_TEMPLATE_STATUS_TEMPLATE = FIGHTER_STATUS_MAX,
	CHARA_CHARA_TEMPLATE_STATUS_MAX,
};