#pragma once

enum {
	FIGHTER_FLOAT_HEALTH,
	FIGHTER_FLOAT_SUPER_METER,
	FIGHTER_FLOAT_INIT_POS_JUMP_Y,
	FIGHTER_FLOAT_CURRENT_X_SPEED,
	FIGHTER_FLOAT_CURRENT_Y_SPEED,
	FIGHTER_FLOAT_INIT_LAUNCH_SPEED,
	FIGHTER_FLOAT_LAUNCH_GRAVITY,
	FIGHTER_FLOAT_LAUNCH_FALL_SPEED_MAX,
	FIGHTER_FLOAT_LAUNCH_SPEED_X,
	FIGHTER_FLOAT_PUSHBACK_PER_FRAME,
	FIGHTER_FLOAT_MANUAL_POS_CHANGE_X,
	FIGHTER_FLOAT_MANUAL_POS_CHANGE_Y,
	FIGHTER_FLOAT_MANUAL_POS_OFFSET_X,
	FIGHTER_FLOAT_MANUAL_POS_OFFSET_Y,
	FIGHTER_FLOAT_DISTANCE_TO_WALL,

	FIGHTER_FLOAT_MAX,
};