#pragma once

enum {
	FIGHTER_INT_JUMP_KIND,
	FIGHTER_INT_DASH_F_WINDOW,
	FIGHTER_INT_DASH_B_WINDOW,
	FIGHTER_INT_KNOCKDOWN_TECH_WINDOW,
	FIGHTER_INT_DASH_AIR_DIR,
	FIGHTER_INT_BACK_CHARGE_FRAMES,
	FIGHTER_INT_BACK_CHARGE_TIMER,
	FIGHTER_INT_DOWN_CHARGE_FRAMES,
	FIGHTER_INT_DOWN_CHARGE_TIMER,
	FIGHTER_INT_PARRY_HEIGHT,
	FIGHTER_INT_INIT_HITLAG_FRAMES,
	FIGHTER_INT_HITLAG_FRAMES,
	FIGHTER_INT_HITSTUN_FRAMES,
	FIGHTER_INT_PUSHBACK_FRAMES,
	FIGHTER_INT_HITSTUN_LEVEL,
	FIGHTER_INT_BLOCKSTUN_HEIGHT,
	FIGHTER_INT_ATTACK_KIND,
	FIGHTER_INT_LANDING_LAG,
	FIGHTER_INT_JUGGLE_VALUE,
	FIGHTER_INT_DAMAGE_SCALE,
	FIGHTER_INT_WAKEUP_SPEED,
	FIGHTER_INT_236_STEP,
	FIGHTER_INT_236_TIMER,
	FIGHTER_INT_214_STEP,
	FIGHTER_INT_214_TIMER,
	FIGHTER_INT_623_STEP,
	FIGHTER_INT_623_TIMER,
	FIGHTER_INT_41236_STEP,
	FIGHTER_INT_41236_TIMER,
	FIGHTER_INT_63214_STEP,
	FIGHTER_INT_63214_TIMER,
	FIGHTER_INT_236236_STEP,
	FIGHTER_INT_236236_TIMER,
	FIGHTER_INT_214214_STEP,
	FIGHTER_INT_214214_TIMER,
	FIGHTER_INT_SPECIAL_LEVEL,
	FIGHTER_INT_MANUAL_POS_CHANGE_FRAMES,
	FIGHTER_INT_BUFFER_HITLAG_STATUS,
	FIGHTER_INT_COMBO_COUNT,
	FIGHTER_INT_FRAME_ADVANTAGE,

	FIGHTER_INT_MAX,
};

enum {
	CHARA_ROY_INT_FIREBALL_LEVEL,
	CHARA_ROY_INT_MAX,
};

enum {
	CHARA_ERIC_INT_DISCHARGE_LEVEL,
	CHARA_ERIC_INT_MAX,
};

enum {
	CHARA_LEON_INT_START,
	CHARA_LEON_INT_MAX,
};

enum {
	CHARA_ANGELICA_INT_START,
	CHARA_ANGELICA_INT_MAX,
};

enum {
	CHARA_NIGHTSABER_INT_START,
	CHARA_NIGHTSABER_INT_MAX,
};

enum {
	CHARA_SULLY_INT_START,
	CHARA_SULLY_INT_MAX,
};

enum {
	CHARA_PRIEST_INT_START,
	CHARA_PRIEST_INT_MAX,
};

enum {
	CHARA_AZIEL_INT_START,
	CHARA_AZIEL_INT_MAX,
};

enum {
	CHARA_BRUNO_INT_START,
	CHARA_BRUNO_INT_MAX,
};

enum {
	CHARA_TESSA_INT_START,
	CHARA_TESSA_INT_MAX,
};

enum {
	CHARA_ALEJANDRO_INT_START,
	CHARA_ALEJANDRO_INT_MAX,
};

enum {
	CHARA_NORMAN_INT_START,
	CHARA_NORMAN_INT_MAX,
};

enum {
	CHARA_ATLAS_INT_START,
	CHARA_ATLAS_INT_MAX,
};

enum {
	CHARA_JULIUS_INT_START,
	CHARA_JULIUS_INT_MAX,
};

enum {
	CHARA_RAMONA_INT_START,
	CHARA_RAMONA_INT_MAX,
};

enum {
	CHARA_ZYAIR_INT_START,
	CHARA_ZYAIR_INT_MAX,
};

enum {
	CHARA_VESUVIUS_INT_START,
	CHARA_VESUVIUS_INT_MAX,
};

enum {
	CHARA_CHARA_TEMPLATE_INT_START,
	CHARA_CHARA_TEMPLATE_INT_MAX,
};