#pragma once

enum {
	GAME_STATE_BATTLE,
	GAME_STATE_MENU,
	GAME_STATE_CHARA_SELECT,
	GAME_STATE_CLOSE,
	GAME_STATE_DEBUG_MENU,
	GAME_STATE_TITLE_SCREEN,
	GAME_STATE_CONTROLS,

	GAME_STATE_MAX,
};

enum {
	GAME_CONTEXT_NORMAL,
	GAME_CONTEXT_TRAINING,
	GAME_CONTEXT_STORY,
	GAME_CONTEXT_ARCADE,
	GAME_CONTEXT_1CPU,
	GAME_CONTEXT_2CPU,
	GAME_CONTEXT_ONLINE,

	GAME_CONTEXT_MAX,
};