#pragma once
#include "PlayerInfo.h"

void set_status_functions(PlayerInfo* player_info);
void tickOnce(PlayerInfo* player_info, SDL_Renderer* renderer);
void check_attack_connections(PlayerInfo *p1, PlayerInfo *p2, SDL_Renderer* renderer, bool visualize_boxes);
int get_event_hit_collide(PlayerInfo* attacker, PlayerInfo* defender, Hitbox *hitbox, Hurtbox *hurtbox);
void event_hit_collide(PlayerInfo *p1, PlayerInfo *p2, Hitbox* p1_hitbox, Hitbox* p2_hitbox);
bool can_counterhit(PlayerInfo* defender, Hitbox* hitbox);
int get_damage_status(int hit_status);

void status_wait(PlayerInfo* player_info);
void enter_status_wait(PlayerInfo* player_info);
void exit_status_wait(PlayerInfo* player_info);
void status_walkf(PlayerInfo* player_info);
void enter_status_walkf(PlayerInfo* player_info);
void exit_status_walkf(PlayerInfo* player_info);
void status_walkb(PlayerInfo* player_info);
void enter_status_walkb(PlayerInfo* player_info);
void exit_status_walkb(PlayerInfo* player_info);
void status_dash(PlayerInfo* player_info);
void enter_status_dash(PlayerInfo* player_info);
void exit_status_dash(PlayerInfo* player_info);
void status_dashb(PlayerInfo* player_info);
void enter_status_dashb(PlayerInfo* player_info);
void exit_status_dashb(PlayerInfo* player_info);
void status_crouchd(PlayerInfo* player_info);
void enter_status_crouchd(PlayerInfo* player_info);
void exit_status_crouchd(PlayerInfo* player_info);
void status_crouch(PlayerInfo* player_info);
void enter_status_crouch(PlayerInfo* player_info);
void exit_status_crouch(PlayerInfo* player_info);
void status_crouchu(PlayerInfo* player_info);
void enter_status_crouchu(PlayerInfo* player_info);
void exit_status_crouchu(PlayerInfo* player_info);
void status_jumpsquat(PlayerInfo* player_info);
void enter_status_jumpsquat(PlayerInfo* player_info);
void exit_status_jumpsquat(PlayerInfo* player_info);
void status_jump(PlayerInfo* player_info);
void enter_status_jump(PlayerInfo* player_info);
void exit_status_jump(PlayerInfo* player_info);
void status_attack(PlayerInfo* player_info);
void enter_status_attack(PlayerInfo* player_info);
void exit_status_attack(PlayerInfo* player_info);
void status_hitstun(PlayerInfo* player_info);
void enter_status_hitstun(PlayerInfo* player_info);
void exit_status_hitstun(PlayerInfo* player_info);
void status_blockstun(PlayerInfo* player_info);
void enter_status_blockstun(PlayerInfo* player_info);
void exit_status_blockstun(PlayerInfo* player_info);
void status_parry_start(PlayerInfo* player_info);
void enter_status_parry_start(PlayerInfo* player_info);
void exit_status_parry_start(PlayerInfo* player_info);
void status_parry(PlayerInfo* player_info);
void enter_status_parry(PlayerInfo* player_info);
void exit_status_parry(PlayerInfo* player_info);