#pragma once
#include "FighterStatus.h"

enum {
	_CHARA_HUNTER_STATUS_START = FIGHTER_STATUS_MAX,
	_CHARA_HUNTER_STATUS_MAX,
};

const int CHARA_HUNTER_STATUS_START = _CHARA_HUNTER_STATUS_START;
const int CHARA_HUNTER_STATUS_MAX = _CHARA_HUNTER_STATUS_MAX;