#pragma once
#include "FighterInt.h"

enum {
	_CHARA_HUNTER_INT_START = FIGHTER_INT_MAX,
	_CHARA_HUNTER_INT_MAX,
};

const int CHARA_HUNTER_INT_START = _CHARA_HUNTER_INT_START;
const int CHARA_HUNTER_INT_MAX = _CHARA_HUNTER_INT_MAX;