#pragma once
//Hard Conventions - MUST be present in the file

#define BASE_VERTEX_LAYER_NAME "vertex"
#define VERTEX_LAYER_ID 0u
#define VERTEX_LAYER_COMPONENTS 3u

#define CORNER_LAYER_NAME "reference"
#define CORNER_LAYER_ID 0u
#define CORNER_LAYER_COMPONENTS 1u

#define NEIGHBOUR_LAYER_NAME "neighbour"

//Soft Conventions - MAY be present in the file

#define LAYER_SEQUENCE0 "sequence"
#define LAYER_NAME_UV0 "uv"
#define LAYER_NORMALS "normal"
#define LAYER_TANGENT "tangent"
#define LAYER_CREASES "creases"
#define LAYER_SELECTION "selection"
#define LAYER_SKIN_WEIGHT "skining_weight"
#define LAYER_SKIN_REFERENCE "skining_reference"
#define LAYER_BLENDSHAPE "blendshape"
#define LAYER_ADD_BLENDSHAPE "addblendshape"
#define LAYER_MATERIAL_ID "material"

/*
ddddddddddoooodoooooooooooollllllllcccccoddooooollldo,.........................';::;;,,,,,'...,::cclllllccc:::;,''.............................,;:::::
dddddddddddddddddddddooooooooooooooollccodooooolllloo;.............................';;,,'....';::::ccccccccc::::;;,,''...............'',,,;::;,',;::::
ddddddddddddddddddddddddddddddddooooolclodooolllllool,.............................,ccc:,'...,:c::;;::cccccccc::::::;;,,'''''''''',,,;::::ccclc;',;:::
ddddddddddddddddddddddddddddddddddddoc:loooolllllloo:.............................';:::;,'..';cc:;,,,;;::cc::::::::::::;;;;;;;;;;;;;;:::::::cclc,';;;;
ddddddddddddddddddddddddddddddddddol:,;loooollllllol;.............................,;:::;,'..';:::;,''',,,;;::::::::::::::;;;::::::::::::::::::c:;,;;;;
ddddddddddddddddddddddddddddddoc:;'...:oooooolllllol'............................';;;::;,'..',::;;,''',,,,,;;;;;;;;;;;;;;;;;;:::::::::::::::::::,,;;;;
dddddddddddddddddddddddddooc:,'.....';loooooooolloo:.............................',;;;:;,'...,;:;;,,,,;;;;;;;;,,,,,,,;;;;;;;;;;;;;;::::;;;;;;;;;,',;;;
dddddddddddddddddddddolc;,'.......,:lodoooooooollol;.............................',;;;;;;''..',;;;,,;;;:cc:::;;;,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;,'',;;:
ddddddddddddddddddlc:,'.....,:lolloddddddddxdollodl,.............................',;;;;;,,'''',,,,,;;:coxOOkxoc:;,,,,,,,;;:::;;:;;;;;;,,,,,;;;,'.',;;:
dddddddddddddddol:'.....,:cloddddddddddddddxxxdoooo;..............................',;,,,,,''',,,;;;::cox0KXXKkoc;;,,,,;;::codddoc:::;,,,,,,;;;'.',;;::
llloooooodddol:;'...,:clodxxxxxdddddddddddooddxxdol,..............................',;,,,,,'''',,;;;;::cloxkkxdl:;;;;;;;:cldOKKK0koc:;;;,,,,,,,'',,;;;:
llllllllllc:,'......cxxxddddddxxxxxxxxdddddoooooddl,.............................'',,,,,,,;;;;::::;;;;;;:cc::::;;;;;;;;:cldkO000kolc:;;,,,,,'.',,;;;;;
cclllllcc:,'.......,lxxdddddddddddddddddoooollooddl,.............................',,,;;;::ccccc::;;,,;;;;;;;;;;;;;;;;;;;:::cllllcc:::;;;;;,'.'',;;;;;,
lcccccc;'..........:oxddddddddoooooooollllllloooooc'............................';::cccccccc:::;;;;;;::::;;;;;;;;;;;;;,,,;;;::;;;;;;;;;;;,,'',;;;;,,'.
cccccc:,..........:oddddddddddoooooooooolooodddooc,............................,clllllllcc::::;;;;::::::::::;;;;;;;;,,,,;;;;;;;;;::;;;;,'''',;;;;;,'..
lllccc:'.........'lxxddxxdddddddddddddddddooodddl,...........................';clllllccccc::::;::::::::::::::;;;;;;,,;;;;;:;::::::::::;,''',,,,,;,,...
llllll;..........:dxxxxxxxxxxxxxxxxxxxxxdddoooddo;..........................';lolllcccccc:::::::cccccc::::::::;;;;;;;;::::::::::::ccccc:;;,,,,,,,'....
lllllc,.........;oxxdxxxxddxxxxxxxxxxxxxddddoooooo:'.......................';clllcccccccc::::ccccccccc::::::::;;;;:::::::::::::::ccccllllc:;,,,,......
ollll:'........'cddddddddddddddddddddddooooooooool:,.......................';clllc:::cccccccccccccc::::::::::::::::::::::::::::cccccllloool:;,,'......
llllc;'........,lddddddddddoooollllllllllccllll:;'.........................';lollc:;,:llllcccccccccccccc:::::::::::::::::::::cccccclllloooooc;'.......
llllc;''''''..';looooodddooooooolllllllllllol:,.........,;,.........'''''''';clllcc::lddddoolllllccccccccccccccccccc::::::::::cccccclllooooool;'......
lccc:,,,,,,'''':lllloodoolllolooooooooolllllol;''......,:c;'.''',,,,,;;;;,,,;clllccccldddddddddddoooolcc:::::::ccccccccc:::::cccccclllloooodoooc,.....
::::;;,;;;;,,'';::clooolccccclllllllllllllccccc:,''''',;::,''',;;;:::::cc::::cllcccccllooooooddddoooddoollllllcc::ccc:::::::cccclllllloooooooodo:'....
;,,,,,;;;;,,,''',;:lll:;;;;:::::::::::::::::::::;,,,,;;:;;,,,,;;::::::cccc::::cc::cllccccllllooolllooolllooooolllllllcc:::::cllccllllloooooooooo;.....
''''',,,,,''''..',:::,''',,;;;;;;;;,,,,;;;;;;;;;,,,,,,;,,,,,,,,;;;;;;:ccc:;;;;;;;:ccc::;;;;:cccccccccccccccllccccccccccccclooollcclllllllllllool;.....
'..''''''''.....',;,'....',,,''''''''''',,,,,''''''''''''',,,'''''',,;:;;,,,,,,,;:::;;,,,,;;;;;;;;;;;;;;:::::::;;;;::c:ccodxddoooollllllc:::cloo;.....
..';;;;;;;;;;;,;;;;;,,,,,,,,,,,,,,,''',,,,,''''''''''...''''.......',,,'''''''',,;,,'''''',,,,,,,,'''',,,,,,,,,'',,;::::ldxxdolloollllllc::looo:'.....
..,::::::;:c:;::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,'''',,,,,'''''''''''''''...''''''''....',,;;;codddollllccccclc:clool:.......
..,:::::;:x0x:;;:;;:dko:;::::::::::::::::::::::::::::::::::::::::;;;;::::::::::::;;;;;;;;,,,,'''''''''',:ccc::::::;,,,:loddollccc:::::::clooo:........
'';:::::;;dXXd;;;;:xXXd;;:clllc:;;;:::::::;;;;;::::::::::::lkkl:::;;cxdc;;;;;;;:::::;;;;;;;;;;;;,,,,,,;;:lddddddddc,,;:loodolc::::::;;::cloo:'........
,,;:::;;;;:kN0l;;;dKXx;;ok00000kl,:x0OOOOkdxkl;;;:oxl::::::dXXd:;;;;xXKo;;;::cc::;;;;;;;;;;;;;:;;;,,;d0x;;looooooo:',;:coddoc:::;;;;;;:clll:..........
,,;::::;;;;l0Nk:;oKXx:;dXN0xdx0N0lc0WXkddooON0l;;dKXd::::;;dNNkollllONKl;lkO0000Oxc;:dOkkkkxl;;ldxxdd0Nk;,;;;;;;;;,',,:lodolc:;;;;;;;::cc:,...........
,';:::::::;;oKXxoKNk:;cOWN00000K0llKNx;;;;,cONOcoKXkc::::::xNWXKKKKXNW0l;cxxxddxKNO:c0WNOxxxlcxKXOOOKNNk;,;;,,,'''''',:loolc:;;;;;;;::c:;'............
.';::::::::;:xNNXNOc;;:xXXxlllodl;lKXd;;::;;lKNKXXkc:::::::kNXxlllld0N0c:dO0000KXW0cc0Nk:;;;;dXKd:;;oKNx;;;;;,,,,,''',:cllc::::::::::::;'.............
.';:::::::::;cx0Kkc;::;cd0KK00K0o;oKKo;::::::dXWNOc;::::::ckN0l;::;cONOldXKOxlldKNO:lKNx:::::xXKl;;;l0Xd;;;;;;,,,,'.',:cc::::::::::::::;,'............
.':::::::::::::cc:;:::::::lloolc:;cooc::::::;oKNOc::::ccc:cx0kc:cc:lOKx:lOKK0OO0XNOclKXd::c::l0X0xdx0NXd;:::::;;;,..',;::::::::::::::cc::,'...........
.,::::::::::::::::::::::::::::::::::::c:::lxOKXOl::cccccc:::c:::cc::clc::clooodoodo:cddl::c:::cdOOOOOOOl::cc::::;,..',,;;::ccccccccccccc:;,'..........
,,;;;;;;;;;;,,,;;;;;;;;;;;;;::::::::::::::cxkxoc::ccccc:::::::ccccc::::cc::::::::::::::::::c:::::::::cc::cccccc::;..'',;::ccccccccccccccc:;'.....,,,..
;;,,,,,,,,,,''',,,''....'''''',;::;,''''''''',,,;;;;,,,,;;;;;;;;::::::::::::::::::::::::::::::::cccccccc:cccccccc;..'',;:cccllccccccccccc;,....',;;,'.
::;;;;;;::;,,,;;;;,'''''''',,;:cl:,'...'..'''',;;,'''''''',,,''',,,,,,,,;,,,,,,,,,,'''',,,,,,,,,;;;;;;;;,,,,;;;;;,..',;:cccllllllllccccc:;'..',;;;,,''
:::::::cc::;;;:::;,,,,,,,,;;:lddo:,',,,,,,,,,;::;,,'',,,,;;;,,,;;;;;;;;;;;,,,,,;;,''..'',,,,'''',,;;,,'............',;::clllllllllllccc:;;,,;;::;;,,''
:c:::cccc:;;::cc:;;;;;;;;;:coxkxl;,;;;,,,,,;;:c:;,,,,,,;:::;;;;:::;;:::::;;;;;::;,,''',,;;;,,,,,;::;;,'''''''...''',;;:ccllllllllllccc:;:ccc:::;;;,'''

*/