#pragma once
#include "FighterString.h"

enum {
	_CHARA_LEON_STRING_START = FIGHTER_STRING_MAX,
	_CHARA_LEON_STRING_MAX,
};

const int CHARA_LEON_STRING_START = _CHARA_LEON_STRING_START;
const int CHARA_LEON_STRING_MAX = _CHARA_LEON_STRING_MAX;