#pragma once
#include "FighterFlag.h"

enum {
	_CHARA_LEON_FLAG_START = FIGHTER_FLAG_MAX,
	_CHARA_LEON_FLAG_MAX,
};

const int CHARA_LEON_FLAG_START = _CHARA_LEON_FLAG_START;
const int CHARA_LEON_FLAG_MAX = _CHARA_LEON_FLAG_MAX;