#pragma once
#include "FighterStatus.h"

enum {
	_CHARA_NIGHTSABER_STATUS_START = FIGHTER_STATUS_MAX,
	_CHARA_NIGHTSABER_STATUS_MAX,
};

const int CHARA_NIGHTSABER_STATUS_START = _CHARA_NIGHTSABER_STATUS_START;
const int CHARA_NIGHTSABER_STATUS_MAX = _CHARA_NIGHTSABER_STATUS_MAX;