#pragma once
#include "FighterFlag.h"

enum {
	_CHARA_NIGHTSABER_FLAG_START = FIGHTER_FLAG_MAX,
	_CHARA_NIGHTSABER_FLAG_MAX,
};

const int CHARA_NIGHTSABER_FLAG_START = _CHARA_NIGHTSABER_FLAG_START;
const int CHARA_NIGHTSABER_FLAG_MAX = _CHARA_NIGHTSABER_FLAG_MAX;