#pragma once
#include "FighterFloat.h"

enum {
	_CHARA_NORMAN_FLOAT_START = FIGHTER_FLOAT_MAX,
	_CHARA_NORMAN_FLOAT_MAX,
};

const int CHARA_NORMAN_FLOAT_START = _CHARA_NORMAN_FLOAT_START;
const int CHARA_NORMAN_FLOAT_MAX = _CHARA_NORMAN_FLOAT_MAX;