#pragma once
#include "FighterStatus.h"

enum {
	_CHARA_NORMAN_STATUS_START = FIGHTER_STATUS_MAX,
	_CHARA_NORMAN_STATUS_MAX,
};

const int CHARA_NORMAN_STATUS_START = _CHARA_NORMAN_STATUS_START;
const int CHARA_NORMAN_STATUS_MAX = _CHARA_NORMAN_STATUS_MAX;