#pragma once

enum {
	CHARA_KIND_ROY,
	CHARA_KIND_ERIC,
	CHARA_KIND_LEON,
	CHARA_KIND_ANGELICA,
	CHARA_KIND_NIGHTSABER,
	CHARA_KIND_SULLY,
	CHARA_KIND_PRIEST,
	CHARA_KIND_AZIEL,
	CHARA_KIND_BRUNO,
	CHARA_KIND_TESSA,
	CHARA_KIND_ALEJANDRO,
	CHARA_KIND_NORMAN,
	CHARA_KIND_ATLAS,
	CHARA_KIND_JULIUS,
	CHARA_KIND_RAMONA,
	CHARA_KIND_ZYAIR,
	CHARA_KIND_VESUVIUS,

	CHARA_KIND_CHAMELEON,

	CHARA_KIND_CHARA_TEMPLATE,
	CHARA_KIND_MAX,
};

enum {
	PROJECTILE_KIND_ROY_FIREBALL,
	PROJECTILE_KIND_ERIC_FIREBALL,
	PROJECTILE_KIND_PROJECTILE_TEMPLATE,

	PROJECTILE_KIND_MAX,
};

enum {
	STAGE_KIND_TRAINING,
	STAGE_KIND_TRAINING_OLD,

	STAGE_KIND_MAX,
};

enum {
	OBJECT_TYPE_FIGHTER,
	OBJECT_TYPE_PROJECTILE,

	OBJECT_TYPE_MAX,
};