#pragma once

enum {
	_PROJECTILE_STATUS_NONE,

	_PROJECTILE_STATUS_MAX,
	_PROJECTILE_STATUS_START_UNIQUE_PROJECTILE_STATUS,
};

const int PROJECTILE_STATUS_NONE = _PROJECTILE_STATUS_NONE;

const int PROJECTILE_STATUS_MAX = _PROJECTILE_STATUS_MAX;
const int PROJECTILE_STATUS_START_UNIQUE_PROJECTILE_STATUS = _PROJECTILE_STATUS_START_UNIQUE_PROJECTILE_STATUS;