#pragma once

enum {
	_PROJECTILE_STATUS_ACTIVATE,
	_PROJECTILE_STATUS_DEACTIVATE,

	_PROJECTILE_STATUS_MAX,
	_PROJECTILE_STATUS_START_UNIQUE_PROJECTILE_STATUS,
};

const int PROJECTILE_STATUS_ACTIVATE = _PROJECTILE_STATUS_ACTIVATE;
const int PROJECTILE_STATUS_DEACTIVATE = _PROJECTILE_STATUS_DEACTIVATE;

const int PROJECTILE_STATUS_MAX = _PROJECTILE_STATUS_MAX;
const int PROJECTILE_STATUS_START_UNIQUE_PROJECTILE_STATUS = _PROJECTILE_STATUS_START_UNIQUE_PROJECTILE_STATUS;