#pragma once

enum {
	_PROJECTILE_STATUS_DEFAULT,
	_PROJECTILE_STATUS_MOVE,
	_PROJECTILE_STATUS_HIT,

	_PROJECTILE_STATUS_MAX,
};

const int PROJECTILE_STATUS_DEFAULT = _PROJECTILE_STATUS_DEFAULT;
const int PROJECTILE_STATUS_MOVE = _PROJECTILE_STATUS_MOVE;
const int PROJECTILE_STATUS_HIT = _PROJECTILE_STATUS_HIT;

const int PROJECTILE_STATUS_MAX = _PROJECTILE_STATUS_MAX;