#pragma once

enum {
	_PROJECTILE_FLOAT_SPEED_X,
	_PROJECTILE_FLOAT_SPEED_Y,

	_PROJECTILE_FLOAT_MAX,
};

const int PROJECTILE_FLOAT_SPEED_X = _PROJECTILE_FLOAT_SPEED_X;
const int PROJECTILE_FLOAT_SPEED_Y = _PROJECTILE_FLOAT_SPEED_Y;

const int PROJECTILE_FLOAT_MAX = _PROJECTILE_FLOAT_MAX;
