#pragma once
#include "ProjectileStatus.h"

enum {
	PROJECTILE_PROJECTILE_TEMPLATE_STATUS_START = PROJECTILE_STATUS_MAX,
	PROJECTILE_PROJECTILE_TEMPLATE_STATUS_TEMPLATE,
	PROJECTILE_PROJECTILE_TEMPLATE_STATUS_MAX,
};