#pragma once
#include "ProjectileInt.h"

enum {
	_PROJECTILE_PROJECTILE_TEMPLATE_INT_START = PROJECTILE_INT_MAX,

	_PROJECTILE_PROJECTILE_TEMPLATE_INT_MAX,
};

const int PROJECTILE_PROJECTILE_TEMPLATE_INT_START = _PROJECTILE_PROJECTILE_TEMPLATE_INT_START;
const int PROJECTILE_PROJECTILE_TEMPLATE_INT_MAX = _PROJECTILE_PROJECTILE_TEMPLATE_INT_MAX;