#pragma once
#include "ProjectileFloat.h"

enum {
	_PROJECTILE_PROJECTILE_TEMPLATE_FLOAT_START = PROJECTILE_FLOAT_MAX,

	_PROJECTILE_PROJECTILE_TEMPLATE_FLOAT_MAX,
};

const int PROJECTILE_PROJECTILE_TEMPLATE_FLOAT_START = _PROJECTILE_PROJECTILE_TEMPLATE_FLOAT_START;
const int PROJECTILE_PROJECTILE_TEMPLATE_FLOAT_MAX = _PROJECTILE_PROJECTILE_TEMPLATE_FLOAT_MAX;