#pragma once
#include "ProjectileFlag.h"

enum {
	_PROJECTILE_PROJECTILE_TEMPLATE_FLAG_START = PROJECTILE_FLAG_MAX,

	_PROJECTILE_PROJECTILE_TEMPLATE_FLAG_MAX,
};

const int PROJECTILE_PROJECTILE_TEMPLATE_FLAG_START = _PROJECTILE_PROJECTILE_TEMPLATE_FLAG_START;
const int PROJECTILE_PROJECTILE_TEMPLATE_FLAG_MAX = _PROJECTILE_PROJECTILE_TEMPLATE_FLAG_MAX;