#pragma once

enum {
	_PROJECTILE_FLAG_ATTACK_HIT,
	_PROJECTILE_FLAG_DESPAWN_ON_OOB,

	_PROJECTILE_FLAG_MAX,
};

const int PROJECTILE_FLAG_ATTACK_HIT = _PROJECTILE_FLAG_ATTACK_HIT;
const int PROJECTILE_FLAG_DESPAWN_ON_OOB = _PROJECTILE_FLAG_DESPAWN_ON_OOB;

const int PROJECTILE_FLAG_MAX = _PROJECTILE_FLAG_MAX;