#pragma once

enum {
	_PROJECTILE_FLAG_HIT,
	_PROJECTILE_FLAG_HIT_IN_STATUS,

	_PROJECTILE_FLAG_MAX,
};

const int PROJECTILE_FLAG_HIT = _PROJECTILE_FLAG_HIT;
const int PROJECTILE_FLAG_HIT_IN_STATUS = _PROJECTILE_FLAG_HIT_IN_STATUS;

const int PROJECTILE_FLAG_MAX = _PROJECTILE_FLAG_MAX;