#pragma once

enum {
	_PROJECTILE_INT_HEALTH,
	_PROJECTILE_INT_ACTIVE_TIME,
	_PROJECTILE_INT_HITLAG_FRAMES,
	_PROJECTILE_INT_INIT_HITLAG_FRAMES,

	_PROJECTILE_INT_MAX,
};

const int PROJECTILE_INT_HEALTH = _PROJECTILE_INT_HEALTH;
const int PROJECTILE_INT_ACTIVE_TIME = _PROJECTILE_INT_ACTIVE_TIME;
const int PROJECTILE_INT_HITLAG_FRAMES = _PROJECTILE_INT_HITLAG_FRAMES;
const int PROJECTILE_INT_INIT_HITLAG_FRAMES = _PROJECTILE_INT_INIT_HITLAG_FRAMES;

const int PROJECTILE_INT_MAX = _PROJECTILE_INT_MAX;