#pragma once
#include "FighterInt.h"

enum {
	_CHARA_RAMONA_INT_START = FIGHTER_INT_MAX,
	_CHARA_RAMONA_INT_MAX,
};

const int CHARA_RAMONA_INT_START = _CHARA_RAMONA_INT_START;
const int CHARA_RAMONA_INT_MAX = _CHARA_RAMONA_INT_MAX;