#include "RowanFireball.h"
#include "RowanFireballConstants.h"

void RowanFireball::load_move_scripts() {
	script("default", [this]() {
		return;
	});
	script("hover", [this]() {
		execute_frame(0, [this]() {
			push_function(&Projectile::NEW_EFFECT, "flame", glm::vec3(0.0, 0.0, 0.0), glm::vec3(0.0, 0.0, 0.0), glm::vec3(1.0), glm::vec4(0.0), glm::vec3(0.0), glm::vec3(0.0), glm::vec3(0.0), glm::vec4(0.0), &projectile_int[PROJECTILE_INT_INIT_HITLAG_FRAMES]);
		});
	});
	script("punched", [this]() {
		execute_frame(1, [this]() {
			push_function(&Projectile::NEW_EFFECT, "flame", glm::vec3(0.0, 0.0, 0.0), glm::vec3(0.0, 0.0, 0.0), glm::vec3(1.0), glm::vec4(0.0), glm::vec3(0.0), glm::vec3(0.0), glm::vec3(0.0), glm::vec4(0.0), &projectile_int[PROJECTILE_INT_INIT_HITLAG_FRAMES]);
			push_function(&Projectile::NEW_PUSHBOX, 0, glm::vec2(-50, -35), glm::vec2(50, 35));
			push_function(&Projectile::NEW_HURTBOX, 0, glm::vec2(-50, -35), glm::vec2(50, 35), HURTBOX_KIND_NORMAL, false, INTANGIBLE_KIND_NONE);
			if (battle_object_manager->fighter[owner_id]->fighter_int[FIGHTER_INT_SPECIAL_LEVEL] == SPECIAL_LEVEL_L) {
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 0, /*Multihit ID*/ 0, /*Damage*/ 30.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 35), HIT_KIND_GROUND | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 10, /*Hitstun*/ 18, /*Blockstun*/ 10, /*Hit Pushback*/ 18.0, /*Block Pushback*/ 18.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 1, /*Multihit ID*/ 0, /*Damage*/ 30.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 5), HIT_KIND_AIR | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 0, /*Hitstun*/ 18, /*Blockstun*/ 0, /*Hit Pushback*/ 23.0, /*Block Pushback*/ 0.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
			}
			if (battle_object_manager->fighter[owner_id]->fighter_int[FIGHTER_INT_SPECIAL_LEVEL] == SPECIAL_LEVEL_M) {
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 0, /*Multihit ID*/ 0, /*Damage*/ 40.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 35), HIT_KIND_GROUND | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 10, /*Hitstun*/ 18, /*Blockstun*/ 10, /*Hit Pushback*/ 18.0, /*Block Pushback*/ 18.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 1, /*Multihit ID*/ 0, /*Damage*/ 40.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 5), HIT_KIND_AIR | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 0, /*Hitstun*/ 18, /*Blockstun*/ 0, /*Hit Pushback*/ 23.0, /*Block Pushback*/ 0.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
			}
			if (battle_object_manager->fighter[owner_id]->fighter_int[FIGHTER_INT_SPECIAL_LEVEL] == SPECIAL_LEVEL_H) {
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 0, /*Multihit ID*/ 0, /*Damage*/ 50.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 35), HIT_KIND_GROUND | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 10, /*Hitstun*/ 18, /*Blockstun*/ 10, /*Hit Pushback*/ 18.0, /*Block Pushback*/ 18.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 1, /*Multihit ID*/ 0, /*Damage*/ 50.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 5), HIT_KIND_AIR | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 0, /*Hitstun*/ 18, /*Blockstun*/ 0, /*Hit Pushback*/ 23.0, /*Block Pushback*/ 0.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
			}
			if (battle_object_manager->fighter[owner_id]->fighter_int[FIGHTER_INT_SPECIAL_LEVEL] == SPECIAL_LEVEL_EX) {
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 0, /*Multihit ID*/ 0, /*Damage*/ 30.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 35), HIT_KIND_GROUND | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 3, /*Blocklag*/ 3, /*Hitstun*/ 18, /*Blockstun*/ 10, /*Hit Pushback*/ 8.0, /*Block Pushback*/ 8.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 1, /*Multihit ID*/ 0, /*Damage*/ 30.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 5), HIT_KIND_AIR | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 3, /*Blocklag*/ 0, /*Hitstun*/ 18, /*Blockstun*/ 0, /*Hit Pushback*/ 23.0, /*Block Pushback*/ 0.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 2, /*Multihit ID*/ 1, /*Damage*/ 30.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 35), HIT_KIND_GROUND | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 10, /*Hitstun*/ 18, /*Blockstun*/ 10, /*Hit Pushback*/ 18.0, /*Block Pushback*/ 18.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 3, /*Multihit ID*/ 1, /*Damage*/ 30.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 5), HIT_KIND_AIR | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 0, /*Hitstun*/ 18, /*Blockstun*/ 0, /*Hit Pushback*/ 23.0, /*Block Pushback*/ 0.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
			}
		});
	});
	script("kicked", [this]() {
		execute_frame(0, [this]() {
			push_function(&Projectile::NEW_EFFECT, "flame", glm::vec3(0.0, 0.0, 0.0), glm::vec3(0.0, 0.0, 0.0), glm::vec3(0.8), glm::vec4(0.0), glm::vec3(0.0), glm::vec3(0.0), glm::vec3(0.0), glm::vec4(0.0), &projectile_int[PROJECTILE_INT_INIT_HITLAG_FRAMES]);
			push_function(&Projectile::NEW_PUSHBOX, 0, glm::vec2(-50, -35), glm::vec2(50, 35));
			push_function(&Projectile::NEW_HURTBOX, 0, glm::vec2(-50, -35), glm::vec2(50, 35), HURTBOX_KIND_NORMAL, false, INTANGIBLE_KIND_NONE);
			if (battle_object_manager->fighter[owner_id]->fighter_int[FIGHTER_INT_SPECIAL_LEVEL] == SPECIAL_LEVEL_L) {
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 0, /*Multihit ID*/ 0, /*Damage*/ 30.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 35), HIT_KIND_GROUND | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 10, /*Hitstun*/ 18, /*Blockstun*/ 10, /*Hit Pushback*/ 18.0, /*Block Pushback*/ 18.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 1, /*Multihit ID*/ 0, /*Damage*/ 30.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 5), HIT_KIND_AIR | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 0, /*Hitstun*/ 18, /*Blockstun*/ 0, /*Hit Pushback*/ 23.0, /*Block Pushback*/ 0.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
			}
			if (battle_object_manager->fighter[owner_id]->fighter_int[FIGHTER_INT_SPECIAL_LEVEL] == SPECIAL_LEVEL_M) {
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 0, /*Multihit ID*/ 0, /*Damage*/ 40.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 35), HIT_KIND_GROUND | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 10, /*Hitstun*/ 18, /*Blockstun*/ 10, /*Hit Pushback*/ 18.0, /*Block Pushback*/ 18.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 1, /*Multihit ID*/ 0, /*Damage*/ 40.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 5), HIT_KIND_AIR | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 0, /*Hitstun*/ 18, /*Blockstun*/ 0, /*Hit Pushback*/ 23.0, /*Block Pushback*/ 0.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
			}
			if (battle_object_manager->fighter[owner_id]->fighter_int[FIGHTER_INT_SPECIAL_LEVEL] == SPECIAL_LEVEL_H) {
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 0, /*Multihit ID*/ 0, /*Damage*/ 50.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 35), HIT_KIND_GROUND | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 10, /*Hitstun*/ 18, /*Blockstun*/ 10, /*Hit Pushback*/ 18.0, /*Block Pushback*/ 18.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 1, /*Multihit ID*/ 0, /*Damage*/ 50.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 5), HIT_KIND_AIR | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 0, /*Hitstun*/ 18, /*Blockstun*/ 0, /*Hit Pushback*/ 23.0, /*Block Pushback*/ 0.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
			}
			if (battle_object_manager->fighter[owner_id]->fighter_int[FIGHTER_INT_SPECIAL_LEVEL] == SPECIAL_LEVEL_EX) {
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 0, /*Multihit ID*/ 0, /*Damage*/ 30.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 35), HIT_KIND_GROUND | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 10, /*Hitstun*/ 18, /*Blockstun*/ 10, /*Hit Pushback*/ 18.0, /*Block Pushback*/ 18.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 1, /*Multihit ID*/ 0, /*Damage*/ 30.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 5), HIT_KIND_AIR | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 0, /*Hitstun*/ 18, /*Blockstun*/ 0, /*Hit Pushback*/ 23.0, /*Block Pushback*/ 0.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 2, /*Multihit ID*/ 1, /*Damage*/ 30.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 35), HIT_KIND_GROUND | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 10, /*Hitstun*/ 18, /*Blockstun*/ 10, /*Hit Pushback*/ 18.0, /*Block Pushback*/ 18.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
				push_function(&Projectile::NEW_HITBOX, /*ID*/ 3, /*Multihit ID*/ 1, /*Damage*/ 30.0, /*Chip Damage*/ 5.0, /*Damage Scale*/ 1, /*Meter Gain*/ 15.0, glm::vec2(-50, -35), glm::vec2(50, 5), HIT_KIND_AIR | HIT_KIND_PROJECTILE, ATTACK_LEVEL_LIGHT, ATTACK_HEIGHT_MID, /*Hitlag*/ 10, /*Blocklag*/ 0, /*Hitstun*/ 18, /*Blockstun*/ 0, /*Hit Pushback*/ 23.0, /*Block Pushback*/ 0.0, /*Hit Status*/ HIT_STATUS_NORMAL, /*Counterhit Status*/ HIT_STATUS_NORMAL, COUNTERHIT_TYPE_COUNTER, /*Juggle Start*/ 1, /*Juggle Increase*/ 1, /*Juggle Max*/ 4, CLANK_KIND_NORMAL, DAMAGE_KIND_CHIP_KO, /*Continue Launch*/ true, /*Disable Hitstun Parry*/ false, /*Launch Info*/ 10.0, 1.3, 15.0, 1.0);
			}
		});
	});
	script("hit", [this]() {

	});
	script("deactivate", [this]() {

	});
}