#pragma once
#include "ProjectileFlag.h"

enum {
	_PROJECTILE_ROWAN_FIREBALL_FLAG_START = PROJECTILE_FLAG_MAX,

	_PROJECTILE_ROWAN_FIREBALL_FLAG_MAX,
};

const int PROJECTILE_ROWAN_FIREBALL_FLAG_START = _PROJECTILE_ROWAN_FIREBALL_FLAG_START;
const int PROJECTILE_ROWAN_FIREBALL_FLAG_MAX = _PROJECTILE_ROWAN_FIREBALL_FLAG_MAX;