#pragma once
#include "ProjectileString.h"

enum {
	_PROJECTILE_ROWAN_FIREBALL_STRING_START = PROJECTILE_STRING_MAX,

	_PROJECTILE_ROWAN_FIREBALL_STRING_MAX,
};

const int PROJECTILE_ROWAN_FIREBALL_STRING_START = _PROJECTILE_ROWAN_FIREBALL_STRING_START;
const int PROJECTILE_ROWAN_FIREBALL_STRING_MAX = _PROJECTILE_ROWAN_FIREBALL_STRING_MAX;