#pragma once
#include "ProjectileStatus.h"

enum {
	PROJECTILE_ROY_FIREBALL_STATUS_START = PROJECTILE_STATUS_MAX,
	PROJECTILE_ROY_FIREBALL_STATUS_HOVER,
	PROJECTILE_ROY_FIREBALL_STATUS_FALL,
	PROJECTILE_ROY_FIREBALL_STATUS_PUNCHED,
	PROJECTILE_ROY_FIREBALL_STATUS_KICKED,
	PROJECTILE_ROY_FIREBALL_STATUS_GROUND,
	PROJECTILE_ROY_FIREBALL_STATUS_MAX,
};