#pragma once
#include "FighterInt.h"

enum {
	_CHARA_ROY_INT_START = FIGHTER_INT_MAX,
	_CHARA_ROY_INT_FIREBALL_LEVEL,
	_CHARA_ROY_INT_MAX,
};

const int CHARA_ROY_INT_START = _CHARA_ROY_INT_START;
const int CHARA_ROY_INT_FIREBALL_LEVEL = _CHARA_ROY_INT_FIREBALL_LEVEL;
const int CHARA_ROY_INT_MAX = _CHARA_ROY_INT_MAX;