#pragma once
#include "FighterStatus.h"

enum {
	CHARA_ROY_STATUS_SPECIAL_FIREBALL_START = FIGHTER_STATUS_MAX,
	CHARA_ROY_STATUS_SPECIAL_FIREBALL_PUNCH,
	CHARA_ROY_STATUS_SPECIAL_FIREBALL_KICK,
	CHARA_ROY_STATUS_SPECIAL_SLIDE,
	CHARA_ROY_STATUS_SPECIAL_SLIDE_FOLLOWUP,
	CHARA_ROY_STATUS_SPECIAL_UPPERCUT_START,
	CHARA_ROY_STATUS_SPECIAL_UPPERCUT,
	CHARA_ROY_STATUS_SPECIAL_UPPERCUT_FALL,
	CHARA_ROY_STATUS_MAX,
};