#pragma once
enum {
	SETTING_KIND_RES_X,
	SETTING_KIND_RES_Y,
	SETTING_KIND_MUSIC_SETTING,
	SETTING_KIND_SE_VOL,
	SETTING_KIND_VC_VOL,
	SETTING_KIND_MUSIC_VOL,
	SETTING_KIND_FULLSCREEN,

	SETTING_KIND_MAX,
};

enum {
	MUSIC_SETTING_STAGE,
	MUSIC_SETTING_CHARA,
	MUSIC_SETTING_SELECT,

	MUSIC_SETTING_MAX,
};