#pragma once

enum {
	STAGE_KIND_TRAINING,
	STAGE_KIND_STREETS,
	STAGE_KIND_ALLEY,
	STAGE_KIND_BAR,
	STAGE_KIND_ROOFTOP,
	STAGE_KIND_CHURCH,
	STAGE_KIND_DOCK,
	STAGE_KIND_HOTEL,
	STAGE_KIND_STADIUM,
	STAGE_KIND_BRAZIL,
	STAGE_KIND_DESERT,
	STAGE_KIND_BAY,
	STAGE_KIND_AIR_ARMADA,
	STAGE_KIND_ZYAIR_LAWN,
	STAGE_KIND_RAMONA_LAB,
	STAGE_KIND_WALLACE_HALLWAY,
	STAGE_KIND_VESUVIUS_LAB,
	STAGE_KIND_CLIFF,

	STAGE_KIND_MAX,
};