#pragma once
#include "FighterFlag.h"

enum {
	_CHARA_TESSA_FLAG_START = FIGHTER_FLAG_MAX,
	_CHARA_TESSA_FLAG_MAX,
};

const int CHARA_TESSA_FLAG_START = _CHARA_TESSA_FLAG_START;
const int CHARA_TESSA_FLAG_MAX = _CHARA_TESSA_FLAG_MAX;