#pragma once
#include "FighterString.h"

enum {
	_CHARA_TESSA_STRING_START = FIGHTER_STRING_MAX,
	_CHARA_TESSA_STRING_MAX,
};

const int CHARA_TESSA_STRING_START = _CHARA_TESSA_STRING_START;
const int CHARA_TESSA_STRING_MAX = _CHARA_TESSA_STRING_MAX;