#pragma once
#include "glm/glm.hpp"

enum {
    TEX_COORD_BOTTOM_LEFT,
    TEX_COORD_BOTTOM_RIGHT,
    TEX_COORD_TOP_RIGHT,
    TEX_COORD_TOP_LEFT,

    TEX_COORD_MAX,
};

struct TextureCoord {
    glm::vec3 pos;
    glm::vec2 tex_coord;
};

const int TEXTURE_RIGHT = 1;
const int TEXTURE_LEFT = 2;
const int TEXTURE_H_MID = TEXTURE_RIGHT | TEXTURE_LEFT;
const int TEXTURE_TOP = 4;
const int TEXTURE_BOTTOM = 8;
const int TEXTURE_V_MID = TEXTURE_TOP | TEXTURE_BOTTOM;
const int TEXTURE_MID = TEXTURE_H_MID | TEXTURE_V_MID;

enum {
    SCREEN_TEXTURE_ORIENTATION_BOTTOM_LEFT,
    SCREEN_TEXTURE_ORIENTATION_BOTTOM_MIDDLE,
    SCREEN_TEXTURE_ORIENTATION_BOTTOM_RIGHT,
    SCREEN_TEXTURE_ORIENTATION_MIDDLE_LEFT,
    SCREEN_TEXTURE_ORIENTATION_MIDDLE,
    SCREEN_TEXTURE_ORIENTATION_MIDDLE_RIGHT,
    SCREEN_TEXTURE_ORIENTATION_TOP_LEFT,
    SCREEN_TEXTURE_ORIENTATION_TOP_MIDDLE,
    SCREEN_TEXTURE_ORIENTATION_TOP_RIGHT,

    SCREEN_TEXTURE_ORIENTATION_MAX,
};