#pragma once
#include "glm/glm.hpp"

enum {
    TEX_COORD_BOTTOM_LEFT,
    TEX_COORD_BOTTOM_RIGHT,
    TEX_COORD_TOP_RIGHT,
    TEX_COORD_TOP_LEFT,

    TEX_COORD_MAX,
};

struct TextureCoord {
    glm::vec3 pos;
    glm::vec2 tex_coord;
};

enum {
    SCREEN_TEXTURE_ORIENTATION_BOTTOM_LEFT,
    SCREEN_TEXTURE_ORIENTATION_BOTTOM_MIDDLE,
    SCREEN_TEXTURE_ORIENTATION_BOTTOM_RIGHT,
    SCREEN_TEXTURE_ORIENTATION_MIDDLE_LEFT,
    SCREEN_TEXTURE_ORIENTATION_MIDDLE,
    SCREEN_TEXTURE_ORIENTATION_MIDDLE_RIGHT,
    SCREEN_TEXTURE_ORIENTATION_TOP_LEFT,
    SCREEN_TEXTURE_ORIENTATION_TOP_MIDDLE,
    SCREEN_TEXTURE_ORIENTATION_TOP_RIGHT,

    SCREEN_TEXTURE_ORIENTATION_MAX
    ,
};