using namespace std;
#include <iostream>
#include "SDL.h"
#include <sstream>
#pragma once
typedef char i8;
typedef unsigned char u8;
typedef short i16;
typedef unsigned short u16;
typedef unsigned int u32;
typedef int i32;
typedef long long i64;
typedef unsigned long long u64;
typedef float f32;

#define global_variable static
#define internal static

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define TICK_RATE_S 60
#define TICK_RATE_MS 1000 / TICK_RATE_S

#define HITBOX_COUNT_MAX 9

int clamp(int min, int value, int max);
int ymlChopInt(string line);
float ymlChopFloat(string line);
string ymlChopString(string line);
bool is_collide(SDL_Rect RectA, SDL_Rect RectB);

enum {
	BUTTON_UP,
	BUTTON_DOWN,
	BUTTON_LEFT,
	BUTTON_RIGHT,
	BUTTON_LP,
	BUTTON_MP,
	BUTTON_HP,
	BUTTON_LK,
	BUTTON_MK,
	BUTTON_HK,
	BUTTON_START,
	BUTTON_DEBUG,
	BUTTON_DEBUG_2,

	BUTTON_MAX,
};

enum {
	CHARA_KIND_ROY,
	CHARA_KIND_ERIC,

	CHARA_KIND_MAX,
};

enum {
	CHARA_STATUS_WAIT,
	CHARA_STATUS_WALKF,
	CHARA_STATUS_WALKB,
	CHARA_STATUS_DASH,
	CHARA_STATUS_DASHB,
	CHARA_STATUS_CROUCHD,
	CHARA_STATUS_CROUCH,
	CHARA_STATUS_CROUCHU,
	CHARA_STATUS_JUMPSQUAT,
	CHARA_STATUS_JUMP,
	CHARA_STATUS_FALL,
	CHARA_STATUS_ATTACK,
	CHARA_STATUS_ATTACK_AIR,
	CHARA_STATUS_GRAB,
	CHARA_STATUS_GRAB_AIR,
	CHARA_STATUS_HITSTUN,
	CHARA_STATUS_HITSTUN_AIR,
	CHARA_STATUS_BLOCKSTUN,
	CHARA_STATUS_PARRY_START,
	CHARA_STATUS_PARRY,
	CHARA_STATUS_HITSTUN_PARRY,
	CHARA_STATUS_CRUMPLE,
	CHARA_STATUS_LAUNCH_START,
	CHARA_STATUS_LAUNCH,
	CHARA_STATUS_CLANK,
	CHARA_STATUS_THROW_TECH,
	CHARA_STATUS_LANDING,
	CHARA_STATUS_LANDING_ATTACK,
	CHARA_STATUS_LANDING_HITSTUN,
	CHARA_STATUS_KNOCKDOWN_START,
	CHARA_STATUS_KNOCKDOWN,
	CHARA_STATUS_WAKEUP,
	CHARA_STATUS_WAKEUP_FAST,
	CHARA_STATUS_WAKEUP_SLOW,

	CHARA_STATUS_MAX,
};

enum {
	CHARA_SITUATION_GROUND,
	CHARA_SITUATION_AIR,
	CHARA_SITUATION_DOWN,

	CHARA_SITUATION_MAX,
};

enum {
	STATUS_GROUP_NORMAL,
	STATUS_GROUP_HITSTUN,
	STATUS_GROUP_CROUCH,

	STATUS_GROUP_MAX,
};

enum {
	DASH_CANCEL_KIND_FOLLOWUP,
	DASH_CANCEL_KIND_INDEFINITE,

	DASH_CANCEL_KIND_MAX,
};

enum {
	CHARA_JUMP_KIND_F,
	CHARA_JUMP_KIND_B,
	CHARA_JUMP_KIND_N,

	CHARA_JUMP_KIND_MAX,
};

enum {
	PARRY_HEIGHT_HIGH,
	PARRY_HEIGHT_MID,
	PARRY_HEIGHT_LOW,

	PARRY_HEIGHT_MAX,
};

enum {
	HITBOX_KIND_NORMAL,
	HITBOX_KIND_BLOCK,

	HITBOX_KIND_MAX,
};

enum {
	ATTACK_LEVEL_LIGHT,
	ATTACK_LEVEL_MEDIUM,
	ATTACK_LEVEL_HEAVY,

	ATTACK_LEVEL_MAX,
};

enum {
	CLANK_KIND_NORMAL,
	CLANK_KIND_CLANK,
	CLANK_KIND_CONTINUE,

	CLANK_KIND_MAX,
};

enum {
	HIT_STATUS_NORMAL,
	HIT_STATUS_CRUMPLE,
	HIT_STATUS_LAUNCH,
	HIT_STATUS_KNOCKDOWN,

	HIT_STATUS_MAX,
};

enum {
	COUNTERHIT_TYPE_NONE,
	COUNTERHIT_TYPE_AERIAL,
	COUNTERHIT_TYPE_NORMAL,

	COUNTERHIT_TYPE_MAX,
};

enum {
	GRABBOX_KIND_NORMAL,
	GRABBOX_KIND_NOTECH,

	GRABBOX_KIND_MAX,
};

enum {
	HURTBOX_KIND_NORMAL,
	HURTBOX_KIND_GRAB,
	HURTBOX_KIND_COUNTER,

	HURTBOX_KIND_MAX,
};

enum {
	INTANGIBLE_KIND_HIGH,
	INTANGIBLE_KIND_MID,
	INTANGIBLE_KIND_LOW,
	INTANGIBLE_KIND_NONE, 
	INTANGIBLE_KIND_THROW,
	INTANGIBLE_KIND_NORMAL,
	INTANGIBLE_KIND_PROJECTILE,
	INTANGIBLE_KIND_INVINCIBLE,
	INTANGIBLE_KIND_ALL,

	INTANGIBLE_KIND_MAX,
};

enum {
	ATTACK_HEIGHT_HIGH,
	ATTACK_HEIGHT_MID,
	ATTACK_HEIGHT_LOW,
	
	ATTACK_HEIGHT_MAX,
};

enum {
	ATTACK_KIND_LP,
	ATTACK_KIND_MP,
	ATTACK_KIND_HP,
	ATTACK_KIND_LK,
	ATTACK_KIND_MK,
	ATTACK_KIND_HK,
	ATTACK_KIND_CLP,
	ATTACK_KIND_CMP,
	ATTACK_KIND_CHP,
	ATTACK_KIND_CLK,
	ATTACK_KIND_CMK,
	ATTACK_KIND_CHK,

	ATTACK_KIND_MAX,
};

enum {
	SITUATION_HIT_GROUND,
	SITUATION_HIT_AIR,
	SITUATION_HIT_DOWN,
	SITUATION_HIT_ALL,

	SITUATION_HIT_MAX,
};

enum {
	CHARA_INT_JUMP_KIND,
	CHARA_INT_DASH_F_WINDOW,
	CHARA_INT_DASH_B_WINDOW,
	CHARA_INT_BACK_CHARGE_FRAMES,
	CHARA_INT_BACK_CHARGE_TIMER,
	CHARA_INT_DOWN_CHARGE_FRAMES,
	CHARA_INT_DOWN_CHARGE_TIMER,
	CHARA_INT_PARRY_HEIGHT,
	CHARA_INT_HITLAG_FRAMES,
	CHARA_INT_HITSTUN_FRAMES,
	CHARA_INT_HITSTUN_LEVEL,
	CHARA_INT_BLOCKSTUN_HEIGHT,
	CHARA_INT_ATTACK_KIND,
	CHARA_INT_LANDING_LAG,
	CHARA_INT_JUGGLE_VALUE,
	CHARA_INT_DAMAGE_SCALE,

	CHARA_INT_MAX,
};

enum {
	CHARA_FLOAT_HEALTH,
	CHARA_FLOAT_SUPER_METER,
	CHARA_FLOAT_INIT_POS_JUMP_Y,
	CHARA_FLOAT_CURRENT_X_SPEED,
	CHARA_FLOAT_CURRENT_Y_SPEED,
	CHARA_FLOAT_INIT_LAUNCH_SPEED,
	CHARA_FLOAT_LAUNCH_GRAVITY,
	CHARA_FLOAT_LAUNCH_FALL_SPEED_MAX,
	CHARA_FLOAT_LAUNCH_SPEED_X,
	CHARA_FLOAT_PUSHBACK_PER_FRAME,

	CHARA_FLOAT_MAX,
};

enum {
	CHARA_FLAG_SHORT_HOP,
	CHARA_FLAG_DASH_CANCEL,
	CHARA_FLAG_ATTACK_CONNECTED,
	CHARA_FLAG_ATTACK_CONNECTED_DURING_STATUS,
	CHARA_FLAG_HAS_ATTACK,
	CHARA_FLAG_HAD_ATTACK_IN_STATUS,
	CHARA_FLAG_SUCCESSFUL_PARRY,
	CHARA_FLAG_PARRY_ACTIVE,
	CHARA_FLAG_PROX_GUARD,
	CHARA_FLAG_ENTER_BLOCKSTUN,
	CHARA_FLAG_ENABLE_COUNTERHIT,

	CHARA_FLAG_MAX,
};

enum {
	CHARA_ROY_INT_PLACEHOLDER,
	CHARA_ROY_INT_MAX,
};

enum {
	CHARA_ROY_FLOAT_PLACEHOLDER,
	CHARA_ROY_FLOAT_MAX,
};

enum {
	CHARA_ROY_FLAG_PLACEHOLDER,
	CHARA_ROY_FLAG_MAX,
};

enum {
	CHARA_ERIC_INT_DISCHARGE_LEVEL,
	CHARA_ERIC_INT_MAX,
};

enum {
	CHARA_ERIC_FLOAT_PLACEHOLDER,
	CHARA_ERIC_FLOAT_MAX,
};

enum {
	CHARA_ERIC_FLAG_OVERDRIVEN,
	CHARA_ERIC_FLAG_MAX,
};

struct Offset {
	int offset_x;
	int offset_y;
};

struct Vec4f {
	int x;
	int y;
	int z;
	int w;
};