#pragma once
#include "FighterFlag.h"

enum {
	_CHARA_VESUVIUS_FLAG_START = FIGHTER_FLAG_MAX,
	_CHARA_VESUVIUS_FLAG_MAX,
};

const int CHARA_VESUVIUS_FLAG_START = _CHARA_VESUVIUS_FLAG_START;
const int CHARA_VESUVIUS_FLAG_MAX = _CHARA_VESUVIUS_FLAG_MAX;