#pragma once
#include "FighterStatus.h"

enum {
	_CHARA_WALLACE_STATUS_START = FIGHTER_STATUS_START_CHARA_STATUS,
	_CHARA_WALLACE_STATUS_MAX,
};

const int CHARA_WALLACE_STATUS_START = _CHARA_WALLACE_STATUS_START;
const int CHARA_WALLACE_STATUS_MAX = _CHARA_WALLACE_STATUS_MAX;