#pragma once
#define WINDOW_WIDTH 1920.0f
#define WINDOW_HEIGHT 1080.0f
#define WINDOW_DEPTH 1920.0f
#define WINDOW_FACTOR WINDOW_WIDTH / WINDOW_HEIGHT
#define SDL_WINDOW_WIDTH (WINDOW_WIDTH / 2)
#define SDL_WINDOW_HEIGHT (WINDOW_HEIGHT / 2)