#pragma once
#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define WINDOW_DEPTH 1920
#define WINDOW_FACTOR (float)WINDOW_WIDTH / (float)WINDOW_HEIGHT
#define SDL_WINDOW_WIDTH (WINDOW_WIDTH / 2)
#define SDL_WINDOW_HEIGHT (WINDOW_HEIGHT / 2)